AutoREALM: AutoRealmApp.cpp File Reference
AutoRealmApp.cpp File Reference
#include "globals.h"
#include <wx/spinctrl.h>
#include <wx/cmdline.h>
#include <wx/arrstr.h>
#include <wx/tokenzr.h>
#include "AutoRealmApp.h"
#include "types.h"
#include "versioninfo.h"
#include "generic_library.h"
#include "Map.xpm"
#include "MapObject.h"
Functions
void InitActionsHandler ()
void InitFillHandler ()
void InitInfoHandler ()
void InitMainHandler ()
void InitMenusHandler ()
void InitOverlayColorsHandler ()
void InitOverlayIconsHandler ()
void InitPushPinHandler ()
void InitSettingsHandler ()
void InitSplashHandler ()
void InitCursorsHandler ()
void InitAutoNameHandler ()
Detailed Description
Function Documentation
void InitActionsHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitAutoNameHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitCursorsHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitFillHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitInfoHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitMainHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitMenusHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitOverlayColorsHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitOverlayIconsHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitPushPinHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitSettingsHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().
void InitSplashHandler ()
Used to initialize xrc files
Referenced by AutoRealmApp::OnInit().