AutoREALM: Matrix3 Class Reference
Matrix3 Class Reference
wraps up a 3x3 matrix in a nice little bundle
#include <matrixmath.h>
Public Member Functions
Matrix3 (double c11=0.0, double c12=0.0, double c13=0.0, double c21=0.0, double c22=0.0, double c23=0.0, double c31=0.0, double c32=0.0, double c33=0.0)
Constructor where the individual elements can be specified.
Matrix3 (const Matrix3 &rhs)
copy constructor
double & cell (int x, int y)
to get a reference to an individual data point I wanted to use [], but you can't have two arguments
const double & cell (int x, int y) const
to get the value of the cell without discarding const qualifiers
bool operator== (const Matrix3 &m) const
are the two matrixes the same?
Matrix3 operator* (const Matrix3 &m) const
allows matrix multiplication
bool isPureOffset () const
determines whether this matrix is a pure offset matrix
Matrix3 & operator= (const Matrix3 &rhs)
allows statemenst of the form matrix2=matrix1
Static Public Member Functions
static Matrix3 rotation (double degrees)
creates a rotation matrix and passes it back
static Matrix3 scale (double xfactor, double yfactor)
creates a scaling matrix and passes it back
static Matrix3 offset (double dx, double dy)
creates an offset matrix and passes it back
static Matrix3 skew (double sx, double sy)
creates a skew matrix and passes it back
static Matrix3 flip (bool xaxis, bool yaxis)
creates a flip matrix and passes it back
Detailed Description
wraps up a 3x3 matrix in a nice little bundle
This matrix class is used mostly for matrix transforms.
Constructor & Destructor Documentation
Matrix3::Matrix3 (double c11 = 0.0, double c12 = 0.0, double c13 = 0.0, double c21 = 0.0, double c22 = 0.0, double c23 = 0.0, double c31 = 0.0, double c32 = 0.0, double c33 = 0.0)
Constructor where the individual elements can be specified.
Parameters:
c11 - the cell to put a value in
c21 - the cell to put a value in
c31 - the cell to put a value in
c12 - the cell to put a value in
c22 - the cell to put a value in
c32 - the cell to put a value in
c13 - the cell to put a value in
c23 - the cell to put a value in
c33 - the cell to put a value in
Referenced by offset(), rotation(), scale(), and skew().
Matrix3::Matrix3 (const Matrix3 & rhs)
copy constructor
Parameters:
rhs The matrix to copy from
References cell().
Member Function Documentation
double & Matrix3::cell (int x, int y)
to get a reference to an individual data point I wanted to use [], but you can't have two arguments
Parameters:
x The column of the cell to be referenced
y The row of the cell to be referenced
Returns:
A reference to the cell
References ERR_INDEX_OUT_OF_BOUNDS.
Referenced by Matrix3(), multiplyPointByMatrix(), operator*(), operator=(), and operator==().
const double & Matrix3::cell (int x, int y) const
to get the value of the cell without discarding const qualifiers
Parameters:
x The column of the cell to be referenced
y The row of the cell to be referenced
Returns:
A const reference to the cell
References ERR_INDEX_OUT_OF_BOUNDS.
Matrix3 Matrix3::flip (bool xaxis, bool yaxis) [static]
creates a flip matrix and passes it back
Parameters:
xaxis Whether or not to allow to flip on the x axis
yaxis Whetehr or not to allow to flip on the y axis
Returns:
A matrix which will flip in the specified directions
References scale().
bool Matrix3::isPureOffset () const
determines whether this matrix is a pure offset matrix
Returns:
true if this is a pure offset matrix, false if not
References offset().
Matrix3 Matrix3::offset (double dx, double dy) [static]
creates an offset matrix and passes it back
Parameters:
dx How much to offset in the x direction
dy How much to offset in the y direction
Returns:
A matrix which will offset by the specified x and y factors
References Matrix3().
Referenced by isPureOffset(), and DrawPrimitive::SetSize().
Matrix3 Matrix3::operator* (const Matrix3 & m) const
allows matrix multiplication
Parameters:
m The matrix to multiply by
Returns:
The new matrix (this * m)
References cell().
Matrix3 & Matrix3::operator= (const Matrix3 & rhs)
allows statemenst of the form matrix2=matrix1
Parameters:
rhs The matrix to copy from
References cell().
bool Matrix3::operator== (const Matrix3 & m) const
are the two matrixes the same?
Parameters:
m The matrix to compare to
Returns:
true if they are, false if they are not
References cell().
Matrix3 Matrix3::rotation (double degrees) [static]
creates a rotation matrix and passes it back
Parameters:
degrees How much rotation should this matrix supply
Returns:
A matrix which will rotate by that many degrees
References deg2rad(), Matrix3(), and rad.
Matrix3 Matrix3::scale (double xfactor, double yfactor) [static]
creates a scaling matrix and passes it back
Parameters:
xfactor The scaling factor in the x direction
yfactor The scaling factor in the y direction
Returns:
A matrix which will scale by the specified x and y factors
References Matrix3().
Referenced by flip(), and DrawPrimitive::SetSize().
Matrix3 Matrix3::skew (double sx, double sy) [static]
creates a skew matrix and passes it back
Parameters:
sx How much to skew in the x direction
sy How much to skew in the y direction
Returns:
A matrix which will skew by the specified x and y factors
References Matrix3().
The documentation for this class was generated from the following files:
matrixmath.h
matrixmath.cpp