AutoREALM: RotateBitmap Class Reference
RotateBitmap Class Reference
Descended from wxDialog, this class is used to display a heading control, allowing the user to select a degree of rotation for a bitmap.
#include <RotateBitmap.h>
Public Member Functions
RotateBitmap ()
Default constructor, used in two step window creation.
RotateBitmap (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=wxT("dialogBox"))
Main constructor, should be the most used.
bool Create (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=wxT("dialogBox"))
Part two of two step window creation.
~RotateBitmap ()
Destructor, cleans up after window is closed.
void setBackgroundBitmap (wxBitmap inbmp)
sets the current selected bitmap using a passed in bitmap
void OnMinusFive (wxCommandEvent &evt)
Called when the "-5" button is pressed.
void OnMinusOne (wxCommandEvent &evt)
Called when the "-1" button is pressed.
void OnPlusOne (wxCommandEvent &evt)
Called when the "+1" button is pressed.
void OnPlusFive (wxCommandEvent &evt)
Called when the "+5" button is pressed.
void OnSpinChange (wxSpinEvent &evt)
Called when the spin control is updated.
void RotatePic (int degrees)
Responsible for updating the picture by rotating it around.
int GetHeading ()
Gets the value of the rotation specified by the user in degrees.
Protected Attributes
int prevheading
wxImage * outside
Detailed Description
Descended from wxDialog, this class is used to display a heading control, allowing the user to select a degree of rotation for a bitmap.
Derived from wxDialog, this class is responsible for selecting the degree of rotation to be used by the main program. It is intended to be displayed modally.
Constructor & Destructor Documentation
RotateBitmap::RotateBitmap (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = wxT("dialogBox"))
Main constructor, should be the most used.
Normal constructor, simply calls the create function. Parameters are identical to parameters for wxDialog::wxDialog()
RotateBitmap::~RotateBitmap ()
Destructor, cleans up after window is closed.
Destructor, cleans up after window is closed and being Destroy()'ed. At this time, just makes sure to free up memory used by the wxImage for the background, but may do more in future.
References outside.
Member Function Documentation
bool RotateBitmap::Create (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = wxT("dialogBox"))
Part two of two step window creation.
This routine is responsible for initializing the dialog window for rotations. It loads up the xrc resource, and makes sure all is ready for first onscreen display. For a blow-by-blow, read the wxLogTrace statements in the code.
Parameters are identical to wxDialog::Create()
Returns:
Required by Create(), but unused
References outside, and RotatePic().
int RotateBitmap::GetHeading ()
Gets the value of the rotation specified by the user in degrees.
This routine is used by any routines which present this rotation box to allow them to find out what the user chose for the rotation.
Returns:
int How many degrees to rotate the item.
References prevheading.
Referenced by MainWin::OnToolRotate().
void RotateBitmap::OnMinusFive (wxCommandEvent & evt)
Called when the "-5" button is pressed.
When the "-5" button is pressed, this handler is called. It decrements the heading by 5, and redraws the picture.
Parameters:
evt wxCommandEvent UNUSED
References prevheading, and RotatePic().
void RotateBitmap::OnMinusOne (wxCommandEvent & evt)
Called when the "-1" button is pressed.
When the "-1" button is pressed, this handler is called. It decrements the heading by 1, and redraws the picture.
Parameters:
evt wxCommandEvent UNUSED
References prevheading, and RotatePic().
void RotateBitmap::OnPlusFive (wxCommandEvent & evt)
Called when the "+5" button is pressed.
When the "+5" button is pressed, this handler is called. It increments the heading by 5, and redraws the picture.
Parameters:
evt wxCommandEvent UNUSED
References prevheading, and RotatePic().
void RotateBitmap::OnPlusOne (wxCommandEvent & evt)
Called when the "+1" button is pressed.
When the "+1" button is pressed, this handler is called. It increments the heading by 1, and redraws the picture.
Parameters:
evt wxCommandEvent UNUSED
References prevheading, and RotatePic().
void RotateBitmap::OnSpinChange (wxSpinEvent & evt)
Called when the spin control is updated.
This routine is called whenever the value in the spin control is updated, either by the user typing (and then exiting the control), or by way of the associated spin buttons. It reads the value in the control, and then redraws the picture with the new heading.
Parameters:
evt wxSpinEvent UNUSED
References prevheading, and RotatePic().
void RotateBitmap::RotatePic (int degrees)
Responsible for updating the picture by rotating it around.
This routine redraws the compass rose, and the picture passed in, showing the user how it would look when the picture is actually rotated.
Parameters:
degrees int how many degrees to rotate the picture.
References outside, prevheading, and rad.
Referenced by Create(), OnMinusFive(), OnMinusOne(), OnPlusFive(), OnPlusOne(), OnSpinChange(), and setBackgroundBitmap().
void RotateBitmap::setBackgroundBitmap (wxBitmap inbmp)
sets the current selected bitmap using a passed in bitmap
sets the current selected bitmap using a passed in bitmap, allowing the user to get a better preview of what the output will look like once the rotation is complete.
Parameters:
inbmp wxBitmap a bitmap to be rotated
References outside, prevheading, and RotatePic().
Member Data Documentation
wxImage* RotateBitmap::outside [protected]
This will contain the bitmap given from the outside, to be show in the dial control. If it is null, then no bitmap has been given.
Referenced by Create(), RotatePic(), setBackgroundBitmap(), and ~RotateBitmap().
int RotateBitmap::prevheading [protected]
This is used to prevent a perpetual re-run of the RotatePic method, by providing a way to let the method decide if it should run
Referenced by GetHeading(), OnMinusFive(), OnMinusOne(), OnPlusFive(), OnPlusOne(), OnSpinChange(), RotatePic(), and setBackgroundBitmap().
The documentation for this class was generated from the following files:
RotateBitmap.h
RotateBitmap.cpp