AutoREALM: ViewPoint Class Reference
ViewPoint Class Reference
used to describe a particular location's view settings on the map including coordinates, overlays, and zoom factor
#include <ViewPoint.h>
Public Member Functions
ViewPoint ()
ViewPoint (arRealRect rect, int cw, int ch)
ViewPoint (arRealRect rect, int cw, int ch, GridObject oldgrid)
ViewPoint (ViewPoint &view, bool useprinter=false)
void CoordToScreen (coord cx, coord cy, int &sx, int &sy)
void CoordToScreen (coord cx, coord cy, coord &sx, coord &sy)
void ScreenToCoord (coord sx, coord sy, coord &cx, coord &cy)
void ScreenToCoord (int sx, int sy, coord &cx, coord &cy)
void DeltaScreenToCoord (int dx, int dy, coord &cx, coord &cy)
void DeltaScreenToCoord (coord dx, coord dy, coord &cx, coord &cy)
void DeltaCoordToScreen (coord cx, coord cy, int &dx, int &dy)
void DeltaCoordToScreen (coord cx, coord cy, coord &dx, coord &dy)
wxPoint CoordToScreenPt (arRealPoint p)
void ScreenToCoordPtArray (VPoints p, int count)
void Zoom (arRealPoint center, float factor, double px=0.5, double py=0.5)
void SetZoomPercent (double percent)
int GetZoomPercent ()
wxRect CoordToScreenRect (arRealRect CoordRect)
arRealRect ScreenToCoordRect (arRealRect CoordRect)
arRealRect ScreenToCoordRect (wxRect rect)
void SetCoordinateSize (int width, int height, bool rescale)
void GetCoordinateSize (int &width, int &height)
void SetCoordinateRect (arRealRect cr)
void GetCoordinateRect (arRealRect &cr)
StyleAttrib FixStyle (StyleAttrib st)
void LoadFromStream (wxFileInputStream &ins)
void LoadFromDOMElement (wxXmlNode E)
wxXmlNode GetAsDOMElement (wxXmlDocument &D)
Public Attributes
wxString Name
wxDC * canvas
OverlaySet VisibleOverlays
OverlaySet ActiveOverlays
unsigned int QuickDraw
GridObject grid
bool OffScreenFullDetail
arRealRect Area
Detailed Description
used to describe a particular location's view settings on the map including coordinates, overlays, and zoom factor
Constructor & Destructor Documentation
ViewPoint::ViewPoint ()
Default construtor. Uses reasonable defaults for all values.
References ActiveOverlays, canvas, Name, OffScreenFullDetail, QuickDraw, and VisibleOverlays.
ViewPoint::ViewPoint (arRealRect rect, int cw, int ch)
Used to set up a viewpoint with more defaults. Basically, this allows the specification of the location of the viewpoint as part of the constructor.
Parameters:
rect The area to be displayed by this viewpoint
cw The clientwidth (how much space the screen should use for it)
ch The clientheight (how much space the screen should use for it)
References ActiveOverlays, Area, canvas, Name, QuickDraw, and VisibleOverlays.
ViewPoint::ViewPoint (arRealRect rect, int cw, int ch, GridObject oldgrid)
Used to set up a viewpoint with more defaults. Basically, this allows the specification of the location of the viewpoint as part of the constructor.
Parameters:
rect The area to be displayed by this viewpoint
cw The clientwidth (how much space the screen should use for it)
ch The clientheight (how much space the screen should use for it)
oldgrid The grid associated with this viewpoint
References ActiveOverlays, Area, canvas, grid, Name, QuickDraw, and VisibleOverlays.
ViewPoint::ViewPoint (ViewPoint & view, bool useprinter = false)
More or less a copy constructor for the viewpoint, but one that also allows to print the viewpoint. As such, it provides a parameter that, if true, reads client settings from the printer, and calculates from there.
Parameters:
view The ViewPoint to copy from
useprinter Whether or not we should use printer settings for client information
Todo:
handle use printer = true
References ActiveOverlays, Area, canvas, grid, Name, QuickDraw, SetCoordinateSize(), and VisibleOverlays.
Member Function Documentation
void ViewPoint::CoordToScreen (coord cx, coord cy, int & sx, int & sy)
Convert map coordinates to screen coordinates
Parameters:
cx input x coordinate
cy input y coordinate
sx output x coordinate
sy output y coordinate
Referenced by CoordToScreenPt(), CoordToScreenRect(), GridObject::DiamondGrid(), GridObject::HexGrid(), GridObject::PolarGrid(), GridObject::RotatedHexGrid(), GridObject::SquareGrid(), and GridObject::TriangleGrid().
void ViewPoint::CoordToScreen (coord cx, coord cy, coord & sx, coord & sy)
Convert map coordinates to screen coordinates
Parameters:
cx input x coordinate
cy input y coordinate
sx output x coordinate
sy output y coordinate
References Area.
wxPoint ViewPoint::CoordToScreenPt (arRealPoint p)
Convert a map coordinate to a screen coordinate in this ViewPoint.
Parameters:
p The map coordinate to convert
Returns:
The screen coordinate for this map coordinate
References CoordToScreen().
wxRect ViewPoint::CoordToScreenRect (arRealRect CoordRect)
Convert map area to screen area.
Parameters:
CoordRect the area of the map to be converted
Returns:
the area on screen for that area of the map
References CoordToScreen().
void ViewPoint::DeltaCoordToScreen (coord cx, coord cy, coord & dx, coord & dy)
Convert area change into screen change. Useful when the area location has updated, and the viewpoint needs to update to reflect the new location
Parameters:
cx input x coordinate
cy input y coordinate
dx output x coordinate
dy output y coordinate
References Area.
void ViewPoint::DeltaCoordToScreen (coord cx, coord cy, int & dx, int & dy)
Convert area change into screen change. Useful when the area location has updated, and the viewpoint needs to update to reflect the new location
Parameters:
cx input x coordinate
cy input y coordinate
dx output x coordinate
dy output y coordinate
References Area.
Referenced by DrawEnclosedFigure(), GridObject::HexGrid(), GridObject::RotatedHexGrid(), and GridObject::TriangleGrid().
void ViewPoint::DeltaScreenToCoord (int dx, int dy, coord & cx, coord & cy)
Convert screen change into area change. Useful when the screen location has updated, and the viewpoint needs to update to reflect the new location
Parameters:
dx input x coordinate
dy input y coordinate
cx output x coordinate
cy output y coordinate
References Area.
Referenced by GetZoomPercent().
void ViewPoint::DeltaScreenToCoord (coord dx, coord dy, coord & cx, coord & cy)
Convert screen change into area change. Useful when the screen location has updated, and the viewpoint needs to update to reflect the new location
Parameters:
dx input x coordinate
dy input y coordinate
cx output x coordinate
cy output y coordinate
References Area.
StyleAttrib ViewPoint::FixStyle (StyleAttrib st)
Responsible for fixing styles for lines. Currently broken, as necessary functions are not yet defined
Parameters:
st The style to be fixed
Todo:
the following if statement requires that IsAComplexLine and GetLineThickness be defined, which they are not. Must wait until
Referenced by DrawEnclosedFigure().
void ViewPoint::GetCoordinateRect (arRealRect & cr)
Get the current map area for this ViewPoint
Parameters:
cr (output) The current map area for this ViewPoint
References Area.
Referenced by SetCoordinateSize(), SetZoomPercent(), and Zoom().
void ViewPoint::GetCoordinateSize (int & width, int & height)
Return the current of the pixels in the drawable screen area
Parameters:
width (output) the width of the pixels
height (output) the height of the pixels
Todo:
Double-check documentation. This might be the width/height of the ViewPoint, not the drawable area.
Referenced by SetZoomPercent().
int ViewPoint::GetZoomPercent ()
Get the zoom value as a whole percent. ie: 50% will be returned as 50, not 0.5;
Returns:
The current zoom value
References DeltaScreenToCoord(), and round().
void ViewPoint::ScreenToCoord (int sx, int sy, coord & cx, coord & cy)
Convert screen coordinates to map coordinates
Parameters:
cx input x coordinate
cy input y coordinate
sx output x coordinate
sy output y coordinate
References ScreenToCoord().
Referenced by ScreenToCoord().
void ViewPoint::ScreenToCoord (coord sx, coord sy, coord & cx, coord & cy)
Convert screen coordinates to map coordinates
Parameters:
cx input x coordinate
cy input y coordinate
sx output x coordinate
sy output y coordinate
References Area.
Referenced by GridObject::DrawGrid(), ScreenToCoordPtArray(), and ScreenToCoordRect().
void ViewPoint::ScreenToCoordPtArray (VPoints p, int count)
Convert a whole array of screen coordinates into map coordinates.
Parameters:
p (input/output) the coordinates to be converted (at the beginning of the function call), and the converted coordinates (at the end of the function call)
count The number of items in p
References ScreenToCoord().
arRealRect ViewPoint::ScreenToCoordRect (arRealRect CoordRect)
Convert screen area to map area
Parameters:
CoordRect the area of the screen to be converted
Returns:
the area of the map represented by that screen area
References ScreenToCoord().
arRealRect ViewPoint::ScreenToCoordRect (wxRect rect)
Convert screen area to map area
Parameters:
rect the area of the screen to be converted
Returns:
the area of the map represented by that screen area
References ScreenToCoord().
void ViewPoint::SetCoordinateRect (arRealRect cr)
Set the map area of the viewpoint to represent the area defined by cr
Parameters:
cr The new map area for this ViewPoint
References Area, and round().
Referenced by SetCoordinateSize(), SetZoomPercent(), and Zoom().
void ViewPoint::SetCoordinateSize (int width, int height, bool rescale)
Set the size of the pixels in the screen.
Parameters:
width the width of the drawable screen area
height the height of the drawable screen area
rescale should the area be rescaled (for instance, due to zooming?)
Todo:
Double-check documentation. This might be the width/height of the ViewPoint, not the drawable area.
Todo:
What the hell? This bit of code confuses/concerns me. Am I really just adding a line which fills an object, and then resets values to the exact same as they were before?
References Area, GetCoordinateRect(), and SetCoordinateRect().
Referenced by ViewPoint().
void ViewPoint::SetZoomPercent (double percent)
Resets the zoom level to a new value. Note that the percentage is the original number. ie: 1600% should have a value passed in of 1600, not 16. 50% should pass in 50, not 0.5.
Parameters:
percent The percentage to zoom to
References GetCoordinateRect(), GetCoordinateSize(), and SetCoordinateRect().
void ViewPoint::Zoom (arRealPoint center, float factor, double px = 0.5, double py = 0.5)
Jump to a specific set of map coordinates, zoom in, and offset the viewpoint by a factor (px,py), allowing the center of the viewpoint to not be in the center of the screen.
Parameters:
center The center of the viewpoint
factor The zoom level
px The offset from the upper left corner of the viewable
py The offset from the upper left corner of the viewable area
References GetCoordinateRect(), and SetCoordinateRect().
Member Data Documentation
OverlaySet ViewPoint::ActiveOverlays
The set of overlays which are to be marked as active in this viewpoint
Referenced by ViewPoint().
arRealRect ViewPoint::Area
The area of the map represented by this ViewPoint
Referenced by CoordToScreen(), DeltaCoordToScreen(), DeltaScreenToCoord(), GetCoordinateRect(), ScreenToCoord(), SetCoordinateRect(), SetCoordinateSize(), and ViewPoint().
wxDC* ViewPoint::canvas
The device context (wxDC) on which to draw the view.
Todo:
Is this a necessary item? Should double-check to see if it can be removed
Referenced by GridObject::DiamondGrid(), GridObject::DrawGrid(), GridObject::HexGrid(), GridObject::PolarGrid(), GridObject::RotatedHexGrid(), GridObject::SquareGrid(), GridObject::TriangleGrid(), and ViewPoint().
GridObject ViewPoint::grid
The grid associated with this viewpoint.
Todo:
This doesn't seem useful. The class doesn't reference it at all. Asking for help on why it is here
Referenced by DrawEnclosedFigure(), and ViewPoint().
wxString ViewPoint::Name
The name of this viewpoint
Referenced by ViewPoint().
bool ViewPoint::OffScreenFullDetail
Should all objects which are offscreen be drawn in full detail?
Referenced by ViewPoint().
unsigned int ViewPoint::QuickDraw
Todo:
document QuickDraw, as I have no idea what it is
Referenced by ViewPoint().
OverlaySet ViewPoint::VisibleOverlays
The set of overlays which are to be visible in this viewpoint
Referenced by ViewPoint().
The documentation for this class was generated from the following files:
ViewPoint.h
ViewPoint.cpp