AutoREALM: MainWin Class Reference
MainWin Class Reference
The main window of the application, controls startup, shutdown, and usage of other dialogs.
#include <MainWin.h>
Public Member Functions
MainWin ()
Minimum constructor, required for subclassing in XRC.
MainWin (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE, const wxString &name=wxT("frame"))
Used to allow subclassing of an XRC item.
bool Create (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE, const wxString &name=wxT("frame"))
Used to allow subclassing of an XRC item.
~MainWin ()
Destructor, does cleanup details.
void UpdateSeed ()
Updates map fractal seed value.
void UpdateGridSize ()
Updates map grid size.
void UpdateBoldUnit ()
Upates the secondary grid size information.
wxBitmap * genBitmap (wxColour col, const wxBitmap &bmp)
generates a color bitmap (used by what could be color buttons) and returns it to the caller
void resetColour (wxString btnName, bool usedlg=true)
resets the color bitmap on a color button
void OnClose (wxCloseEvent &evt)
Checks to make sure user meant to close the app.
void OnToolSelect (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolOpen (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSave (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolPan (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRuler (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolMeasurementString (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRepaint (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolUndo (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRedo (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolReadOnly (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFreehand (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolLine (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolPolyline (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolCurve (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolPolycurve (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolMainColor (wxCommandEvent &evt)
Sets the main foreground color as specified by the user.
void OnToolFillColor (wxCommandEvent &evt)
Sets the main fill color as specified by the user.
void OnToolFillPattern (wxCommandEvent &evt)
Sets the main fill pattern as specified by the user.
void OnToolOutlineColor (wxCommandEvent &evt)
Sets the main outline color as specified by the user.
void OnToolBackgroundColor (wxCommandEvent &evt)
Sets the main background color as specified by the user.
void OnToolGridColor (wxCommandEvent &evt)
Sets the main grid color as specified by the user.
void OnToolShowColorTranslationManager (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolTranslateColor (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolInverseTranslateColor (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRectangle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolCircle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolPolygon (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolArc (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRosetteChartLines (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolText (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolCurvedText (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolHyperlinkPopup (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGroup (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolUngroup (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolDecompose (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFracFreehand (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFracLine (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFracPolyline (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFracCurve (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFracPolycurve (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolAlign (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolFlip (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSkew (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRotate (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolScale (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolMove (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRotate90 (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRotate45 (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolArray (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolOrder (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolToggleOverlayTags (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolToggleDesignGrid (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolToggleGravitySnap (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolToggleGridSnap (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolToggleGravitySnapAlongLinesAndCurves (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRotateSnappedObjects (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSendToBack (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSendBackward (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolBringForward (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolBringToFront (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolPaste (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolCopy (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolCut (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolDelete (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolScalpel (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGlue (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSingleIcon (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSquarePlacement (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolDiamondPlacement (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolRandomPlacement (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolDefineSelectionAsSymbol (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolSymbolLibrary (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphNone (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphSquare (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphHex (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphRHex (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphTriangle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphDiamond (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphHDiamond (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolGraphCircle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolLineStyle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolEndLineStyle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolBeginLineStyle (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnToolZoom (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnVertScroll (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnHorzScroll (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnTxtXSizeChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnTxtYSizeChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnAspectChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnPushpinChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnOverlayChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnOverlayListChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnRoughnessScroll (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnSeedSpin (wxSpinEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnSeedText (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnImgSizeChange (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnImgDensityChange (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnGridSizeChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnSldgridSizeChange (wxScrollEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnBoldUnitChange (wxSpinEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnTxtBoldUnitChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnPriGridStyleChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void OnSecGridStyleChange (wxCommandEvent &evt)
Stub routine for wxWidgets, not used yet.
void FileExit (wxCommandEvent &evt)
Called by clicking File->Exit.
void HelpAbout (wxCommandEvent &evt)
Called by clicking Help->About.
Public Attributes
wxImageList OverlayImages
Protected Attributes
wxConfig * cfg
FillPattern * fill
Detailed Description
The main window of the application, controls startup, shutdown, and usage of other dialogs.
This class is the main window of the AutoREALM application. It is what does the real work. AutoRealmApp, a required class (as in we must derive a class from wxApp), simply creates a MainWin, and fires things off from there.
Todo:
Add event dispatchers for all menubar IDs
Make sure that bmpMainMap should be a wxStaticBitmap. And if it should not, then do something about it.
Fix up the slider controls to generate proper scroll events. Basically, learn how to do it, and then do it for all sliders
Constructor & Destructor Documentation
MainWin::MainWin () [inline]
Minimum constructor, required for subclassing in XRC.
The following constructor should only be used in conjunction with the Create() method below.
MainWin::MainWin (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_FRAME_STYLE, const wxString & name = wxT("frame"))
Used to allow subclassing of an XRC item.
Generally speaking, this will be used in code of the following form:
 mainwin = new MainWin(NULL, XRCID("frmMain"), wxT("frmMain"));
MainWin::~MainWin ()
Destructor, does cleanup details.
Destructor. Cleans up the items from the window which need to be cleaned up, and lets everything close successfully.
References cfg.
Member Function Documentation
bool MainWin::Create (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_FRAME_STYLE, const wxString & name = wxT("frame"))
Used to allow subclassing of an XRC item.
Generally speaking, this will be used in code of the following form:
 mainwin->Create(NULL, XRCID("frmMain"), wxT("frmMain"));
Returns:
required by wxWidgets, but ignored
References cfg, and resetColour().
void MainWin::FileExit (wxCommandEvent & evt)
Called by clicking File->Exit.
This routine just calls Close(), but doesn't force the application to close. This lets the OnClose() ask the user if we should close (to prevent accidental program exit).
Parameters:
evt UNUSED
wxBitmap * MainWin::genBitmap (wxColour col, const wxBitmap & bmp)
generates a color bitmap (used by what could be color buttons) and returns it to the caller
This routine is a convenience routine, used by the color buttons which set main color, background color, outline color, etc. It takes a wxColour and a bitmap, and returns a new bitmap with the same dimensions as the bitmap given which is a solid block of color that matches the wxColour paramter.
Parameters:
col This parameter is a wxColour parameter, and is what should be used to fill the generated bitmap.
bmp This parameter is used to keep the bitmaps the same size on the user's screen. After all, the screen should be consistent, and having bitmaps of different sizes will be confusing. This is a cross check, to make sure they stay that way.
Returns:
A new bitmap will be allocated on the heap. It is the user's responsibility to delete it! The bitmap will be a simple rectangle filled with the specified color.
Referenced by resetColour().
void MainWin::HelpAbout (wxCommandEvent & evt)
Called by clicking Help->About.
This routine will summon up the About box. First, it loads the XRC, then sets the version label which is stored in versioninfo, and finally it displays it. Once the user had clicked "OK", it will close the dialog box.
Parameters:
evt UNUSED
void MainWin::OnClose (wxCloseEvent & evt)
Checks to make sure user meant to close the app.
Called as an event handler, and is located here in the main area as a fallback. It should prevent accidental exit by the user, while avoiding making it difficult to do so.
Parameters:
evt An event identifier passed in from wxWidgets to this window.
void MainWin::OnToolAlign (wxCommandEvent & evt)
Stub routine for wxWidgets, not used yet.
Todo:
Finish the work on using the alignment dialog, now that the code is in place for it.
void MainWin::OnToolBackgroundColor (wxCommandEvent & evt)
Sets the main background color as specified by the user.
This routine (and the other OnTool*Color routines) are all very similar. They simply call resetColour, telling it which button to use. They all receive an event which is entirely unused by us, but which wxWidgets gives to use anyway.
Parameters:
evt UNUSED
References resetColour().
void MainWin::OnToolFillColor (wxCommandEvent & evt)
Sets the main fill color as specified by the user.
This routine (and the other OnTool*Color routines) are all very similar. They simply call resetColour, telling it which button to use. They all receive an event which is entirely unused by us, but which wxWidgets gives to use anyway.
Parameters:
evt UNUSED
References resetColour().
void MainWin::OnToolFillPattern (wxCommandEvent & evt)
Sets the main fill pattern as specified by the user.
When clicked, this button brings up a small dialog box which allows the user to select the fill pattern of his choice. It will then copy that fill pattern to the various bitmap labels for the bitmap button, and return back to the main program. This allows the bitmaps to be copied away and used for fills later.
Parameters:
evt UNUSED
References fill, FillPattern::getCurrentBitmap(), and FillPattern::setCurrentBitmap().
void MainWin::OnToolGridColor (wxCommandEvent & evt)
Sets the main grid color as specified by the user.
This routine (and the other OnTool*Color routines) are all very similar. They simply call resetColour, telling it which button to use. They all receive an event which is entirely unused by us, but which wxWidgets gives to use anyway.
Parameters:
evt UNUSED
References resetColour().
void MainWin::OnToolMainColor (wxCommandEvent & evt)
Sets the main foreground color as specified by the user.
This routine (and the other OnTool*Color routines) are all very similar. They simply call resetColour, telling it which button to use. They all receive an event which is entirely unused by us, but which wxWidgets gives to use anyway.
Parameters:
evt UNUSED
References resetColour().
void MainWin::OnToolOutlineColor (wxCommandEvent & evt)
Sets the main outline color as specified by the user.
This routine (and the other OnTool*Color routines) are all very similar. They simply call resetColour, telling it which button to use. They all receive an event which is entirely unused by us, but which wxWidgets gives to use anyway.
Parameters:
evt UNUSED
References resetColour().
void MainWin::OnToolRotate (wxCommandEvent & evt)
Stub routine for wxWidgets, not used yet.
Todo:
finish the OnToolRotate method, now that the form for it is done
References RotateBitmap::GetHeading().
void MainWin::resetColour (wxString btnName, bool usedlg = true)
resets the color bitmap on a color button
This routine is used both during window initialization and regular runtime. As such, it should ask nothing during initialization, but should do so during runtime.
Basically, this routine will take the name of a button on the screen, and replace the bitmap on that button with another bitmap. In this case, the replacement bitmap will be one produced by genBitmap (above), and so will be just a simple rectangle filled with a single solid color.
It's worth noting that I am doing something kind of sneaky here. The wxBitmapButton class has a foreground color, but does not use it. I'm stored the value of the color that the user chooses in that foreground color member, and retrieve it when I need it.
Parameters:
btnName The name of the button on the screen to be reset.
usedlg (Default value = true) If usedlg is false, then the window is assumed to be initializing. So, instead of asking for a colour before the user even sees a usable window, we simply take the current foreground color of the button, and use it for the bitmap. Otherwise, ask for the color, and reset it where possible.
References genBitmap().
Referenced by Create(), OnToolBackgroundColor(), OnToolFillColor(), OnToolGridColor(), OnToolMainColor(), and OnToolOutlineColor().
void MainWin::UpdateBoldUnit ()
Upates the secondary grid size information.
Again, a routine created to share code between two separate items updating the same information
void MainWin::UpdateGridSize ()
Updates map grid size.
This routine is used to update the grid size, as it can be called from two places (similar to UpdateSeed above).
void MainWin::UpdateSeed ()
Updates map fractal seed value.
This routine is used to update the fractal seed value, and is in place because two separate event styles can trigger the same code (namely, wxSpinEvent and wxCommandEvent)
Member Data Documentation
wxConfig* MainWin::cfg [protected]
This is used to read and write configuration values from the application. It is of type wxConfig, which already exists on all platforms, and reads/saves its data correctly on them (for instance, using the registry on Windows)
Referenced by Create(), and ~MainWin().
FillPattern* MainWin::fill [protected]
This is used for setting/maintaining the fill patterns
Referenced by OnToolFillPattern().
The documentation for this class was generated from the following files:
MainWin.h
MainWin.cpp