AutoREALM: GridObject Class Reference
GridObject Class Reference
This class is responsible for manipulating the grids which are shown to the user.
#include <GraphGrid.h>
Public Member Functions
GridObject ()
Default constructor.
GridObject (GridObject &oldgrid)
Secondary constructor.
double GetUnitLength ()
returns the length of a given unit on this graph
void SetMeasurementUnits (int index)
Sets the default unit of measure.
void SquareGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a square grid on the screen.
void HexGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a hex grid on the screen.
void TriangleGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a triangular grid on the screen.
void RotatedHexGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a rotatex hex grid on the screen.
void DiamondGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num, float squash)
Draws a diamond grid on the screen.
void PolarGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a polar grid on the screen.
void DrawGrid (ViewPoint &v)
Responsible for drawing the grid on a wxDC.
void SetGraphUnits (int index, int gridSize)
Responsible for determing the size of the cells, and how much territory those cells cover.
wxXmlNode GetAsDOMElement (wxXmlDocument &D)
void LoadFromDOMElement (const wxXmlNode &e)
void LoadFromStream (wxFileInputStream &ins, int version)
void FillPopupMenu (wxMenu &Menu, wxCommandEventFunction *action)
Builds the popup menu showing the different units of measure.
void SetMeasurementUnitChecks (wxMenu &Menu)
Checks off the current unit of measure, and unchecks the rest.
void FillComboList (wxComboBox &UnitComboBox)
Puts the units of measure into a combobox.
double Convert (double dist, int unitindex)
Converts distances from one scale to another.
void SetGridPenStyle (wxDC *canvas, GridPenStyle style, GridPenStyle defaultstyle)
Set the pen style for the grid.
void bringGridForward ()
void sendGridBackward ()
int getGridPosition ()
Public Attributes
double GraphScale
double GraphUnitConvert
wxString GraphUnits
int CurrentGraphUnits
int CurrentGridSize
TGraphGrid GridType
int GridBoldUnits
unsigned int GridPosition
unsigned short GridFlags
GridPenStyle PrimaryGridStyle
GridPenStyle SecondaryGridStyle
Detailed Description
This class is responsible for manipulating the grids which are shown to the user.
Todo:
Provide better documentation for this when it's relationship to other classes is more clearly understood.
Make the member variables into protected variables as soon as possible, providing get/set methods.
Constructor & Destructor Documentation
GridObject::GridObject ()
Default constructor.
Creates a new grid object, and initializes it with sensible defaults
References CurrentGraphUnits, CurrentGridSize, gpsDefault, GraphScale, GraphUnits, GridBoldUnits, GridFlags, GridType, gtNone, PrimaryGridStyle, and SecondaryGridStyle.
GridObject::GridObject (GridObject & oldgrid)
Secondary constructor.
Creates a new grid object, using the defaults from the parameter oldgrid.
Parameters:
oldgrid the GridObject from which to copy the settings.
References CurrentGraphUnits, CurrentGridSize, GraphScale, GraphUnits, GridBoldUnits, GridFlags, GridType, PrimaryGridStyle, and SecondaryGridStyle.
Member Function Documentation
void GridObject::bringGridForward ()
Move the grid up one layer
References GridPosition.
double GridObject::Convert (double dist, int unitindex)
Converts distances from one scale to another.
This routine takes a distance between two points, and converts and scales them to be a distance between two points on a new grid scale.
Parameters:
dist The distance to be converted
unitindex The new scale's index in the UnitTable.
References CurrentGraphUnits, CurrentGridSize, GraphScale, and UnitTableLen.
void GridObject::DiamondGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num, float squash)
Draws a diamond grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many squares to go be drawn at a time, used for drawing the secondary grid in boldface
squash How much to squash the grid. Used to draw the half-height diamond grid
References ViewPoint::canvas, ViewPoint::CoordToScreen(), and CurrentGridSize.
Referenced by DrawGrid().
void GridObject::DrawGrid (ViewPoint & v)
Responsible for drawing the grid on a wxDC.
Todo:
Need to document this after coding it up.
References ViewPoint::canvas, CurrentGridColor(), DiamondGrid(), gpsBold, gpsSingle, GridBoldUnits, GridType, gtDiamond, gtHalfDiamond, gtHex, gtNone, gtPolar, gtRotatedHex, gtSquare, gtTriangle, HexGrid(), PolarGrid(), PrimaryGridStyle, RotatedHexGrid(), ViewPoint::ScreenToCoord(), SecondaryGridStyle, SetGridPenStyle(), SquareGrid(), and TriangleGrid().
void GridObject::FillComboList (wxComboBox & UnitComboBox)
Puts the units of measure into a combobox.
This routine clears the contents of a combobox, and then puts the units of measure into the list attached to the combobox.
Parameters:
UnitComboBox The combobox which will accept all the units of measure. It must be ready to accept them.
References UnitTableLen.
void GridObject::FillPopupMenu (wxMenu & Menu, wxCommandEventFunction * action)
Builds the popup menu showing the different units of measure.
Fills the menu (which must already be constructed and valid) with the entries listed in the UnitTable.
Parameters:
Menu The menu to be filled
action The event handler to call when these items are clicked
Todo:
Verify that this Menu.Connect call is correct, it may have
References UnitTableLen.
int GridObject::getGridPosition ()
Get the current grid's layer number
Returns:
An int containing the layer number of the grid
References GridPosition.
void GridObject::HexGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a hex grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many squares to go be drawn at a time, used for drawing the secondary grid in boldface
References ViewPoint::canvas, ViewPoint::CoordToScreen(), CurrentGridSize, and ViewPoint::DeltaCoordToScreen().
Referenced by DrawGrid().
void GridObject::LoadFromStream (wxFileInputStream & ins, int version)
Todo:
must add stream and version parameters here. Original function call: procedure LoadFromStream(stream:TStream; version:integer);
References CurrentGraphUnits, CurrentGridSize, gpsDefault, GraphScale, GraphUnitConvert, GraphUnits, GridBoldUnits, GridFlags, GridPosition, GridType, PrimaryGridStyle, and SecondaryGridStyle.
void GridObject::PolarGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a polar grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many cells to go be drawn at a time, used for drawing the secondary grid in boldface
References ViewPoint::canvas, ViewPoint::CoordToScreen(), and CurrentGridSize.
Referenced by DrawGrid().
void GridObject::RotatedHexGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a rotatex hex grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many squares to go be drawn at a time, used for drawing the secondary grid in boldface
References ViewPoint::canvas, ViewPoint::CoordToScreen(), CurrentGridSize, and ViewPoint::DeltaCoordToScreen().
Referenced by DrawGrid().
void GridObject::sendGridBackward ()
Move the grid down one layer
References GridPosition.
void GridObject::SetGraphUnits (int index, int gridSize)
Responsible for determing the size of the cells, and how much territory those cells cover.
Todo:
Document this better once it's better understood.
References CurrentGraphUnits, CurrentGridSize, unittype::factor, GraphUnitConvert, GraphUnits, unittype::name, and UnitTableLen.
Referenced by SetMeasurementUnits().
void GridObject::SetGridPenStyle (wxDC * canvas, GridPenStyle style, GridPenStyle defaultstyle)
Set the pen style for the grid.
This routine sets the pen style to any of the styles in GridPenStyle. Note that the pen style is only set for the wxDC which is passed in.
Parameters:
canvas The wxDC which is to have the penstyle updated.
style The style of grid which is desired
defaultstyle The default style of the grid, if none is specified using style
References gpsBold, gpsDash, gpsDashDot, gpsDashDotDot, gpsDefault, gpsDot, and gpsSingle.
Referenced by DrawGrid().
void GridObject::SetMeasurementUnitChecks (wxMenu & Menu)
Checks off the current unit of measure, and unchecks the rest.
This routine cycles through the listing of items on the measurements menu, and makes sure that only the current unit of measure is checked off.
Parameters:
Menu the menu to cycle through
References CurrentGraphUnits, and UnitTableLen.
void GridObject::SetMeasurementUnits (int index)
Sets the default unit of measure.
Set the default unit of measure to the unit listed in the UnitTable.
Parameters:
index The index entry of the unit of measure listen in the UnitTable.
Todo:
Map.SetModified(modUnitType);
References CurrentGraphUnits, CurrentGridSize, and SetGraphUnits().
void GridObject::SquareGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a square grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many squares to go be drawn at a time, used for drawing the secondary grid in boldface
References ViewPoint::canvas, ViewPoint::CoordToScreen(), and CurrentGridSize.
Referenced by DrawGrid().
void GridObject::TriangleGrid (ViewPoint view, wxRect clip, coord left, coord right, coord top, coord bottom, coord width, coord height, int num)
Draws a triangular grid on the screen.
Parameters:
view The ViewPoint on which to draw this graph
clip The clipping region on screen for this viewpoint
left The left edge of the map
right The right edge of the map
top The top edge of the map
bottom The bottom edge of the map
width The width of the map
height The height of the map
num How many squares to go be drawn at a time, used for drawing the secondary grid in boldface
References ViewPoint::canvas, ViewPoint::CoordToScreen(), CurrentGridSize, and ViewPoint::DeltaCoordToScreen().
Referenced by DrawGrid().
Member Data Documentation
int GridObject::CurrentGraphUnits
The index into the UnitTable for the current graph units
Referenced by Convert(), GridObject(), LoadFromStream(), SetGraphUnits(), SetMeasurementUnitChecks(), and SetMeasurementUnits().
int GridObject::CurrentGridSize
The current size of a given cell on the grid
Referenced by Convert(), DiamondGrid(), GetUnitLength(), GridObject(), HexGrid(), LoadFromStream(), PolarGrid(), RotatedHexGrid(), SetGraphUnits(), SetMeasurementUnits(), SquareGrid(), and TriangleGrid().
double GridObject::GraphScale
Used to determine the distance each cell of the grid can show, calculated as 1 cell equals this many inches.
Referenced by Convert(), DrawEnclosedFigure(), GetUnitLength(), GridObject(), and LoadFromStream().
double GridObject::GraphUnitConvert
The inverse of the GraphScale, used to give a distance in inches. Calculated as 1 inch equals this many cells.
Referenced by DrawEnclosedFigure(), GetUnitLength(), LoadFromStream(), and SetGraphUnits().
wxString GridObject::GraphUnits
The name of the scale (for instance, inches, centimeters, miles, etc)
Referenced by GridObject(), LoadFromStream(), and SetGraphUnits().
int GridObject::GridBoldUnits
Todo:
Unsure of the meaning of this variable. Fix
Referenced by DrawGrid(), GridObject(), and LoadFromStream().
unsigned short GridObject::GridFlags
Todo:
Unsure of the meaning of this variable. Fix
Referenced by GridObject(), and LoadFromStream().
unsigned int GridObject::GridPosition
Todo:
Unsure of the meaning of this variable. Fix
Referenced by bringGridForward(), getGridPosition(), LoadFromStream(), and sendGridBackward().
TGraphGrid GridObject::GridType
The type of grid to be displayed
Referenced by DrawGrid(), GridObject(), and LoadFromStream().
GridPenStyle GridObject::PrimaryGridStyle
Each grid can have cells. Each cell can contain a secondary grid, which also has a style. The Primary Grid Style holds the style of the main grid, while the Secondary Grid Style holds the style of the secondary grid,
Referenced by DrawGrid(), GridObject(), and LoadFromStream().
GridPenStyle GridObject::SecondaryGridStyle
Each grid can have cells. Each cell can contain a secondary grid, which also has a style. The Primary Grid Style holds the style of the main grid, while the Secondary Grid Style holds the style of the secondary grid,
Referenced by DrawGrid(), GridObject(), and LoadFromStream().
The documentation for this class was generated from the following files:
GraphGrid.h
GraphGrid.cpp