AutoREALM: FillPattern Class Reference
FillPattern Class Reference
Descended from wxDialog, this class is used to display a list of fill patterns and allow the user to select one of them.
#include <FillPattern.h>
Public Member Functions
FillPattern ()
Default constructor, used in two step window creation.
FillPattern (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=wxT("dialogBox"))
Main constructor, should be the most used.
bool Create (wxWindow *parent, wxWindowID id, const wxString &title, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE, const wxString &name=wxT("dialogBox"))
Part two of two step window creation.
void OnCancel (wxCommandEvent &evt)
Overriding behavior when OnCancel is called, so that we revert the bitmap stored in this dialog for others to use.
void OnSelectPattern (wxMouseEvent &evt)
Used for single click in window, activated when button released.
void OnChangePattern (wxMouseEvent &evt)
Used for double click in window.
void setCurrentBitmap (wxBitmap inbmp)
sets the current selected bitmap using a passed in bitmap
void setCurrentBitmap (wxString resName)
sets the current selected bitmap used a string resource name
void setCurrentBitmap (int patternnum)
sets the current selected bitmap used a string resource name
wxBitmap getCurrentBitmap ()
returns a copy of the current selected bitmap
Protected Attributes
wxBitmap prevbmp
Detailed Description
Descended from wxDialog, this class is used to display a list of fill patterns and allow the user to select one of them.
Derived from wxDialog, this class is responsible for selecting the fill pattern to be used by the main program. It is intended to be displayed modally.
Constructor & Destructor Documentation
FillPattern::FillPattern (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = wxT("dialogBox"))
Main constructor, should be the most used.
Normal constructor, simply calls the create function. Parameters are identical to parameters for wxDialog::wxDialog()
Member Function Documentation
bool FillPattern::Create (wxWindow * parent, wxWindowID id, const wxString & title, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE, const wxString & name = wxT("dialogBox"))
Part two of two step window creation.
This routine is responsible for initializing the dialog window for fill patterns. It loads up the xrc resource, and makes sure all is ready for first onscreen display. For a blow-by-blow, read the wxLogTrace statements in the code.
Parameters are identical to wxDialog::Create()
Returns:
Required by Create(), but unused
References prevbmp, and setCurrentBitmap().
wxBitmap FillPattern::getCurrentBitmap ()
returns a copy of the current selected bitmap
This routine returns a copy of the currently selected bitmap to be used for the current fill pattern.
Returns:
wxBitmap this is the bitmap which has been selected by the user.
Referenced by MainWin::OnToolFillPattern().
void FillPattern::OnCancel (wxCommandEvent & evt)
Overriding behavior when OnCancel is called, so that we revert the bitmap stored in this dialog for others to use.
Override of OnCancel to return to the previous bitmap pattern
Parameters:
evt UNUSED
References prevbmp, and setCurrentBitmap().
void FillPattern::OnChangePattern (wxMouseEvent & evt)
Used for double click in window.
This routine determines which bitmap was clicked, and notes it for future reference (when either it is double-clicked, or when the ok button is clicked).
Parameters:
evt wxMouseEvent Used to indicate the wxStaticBitmap in which the user clicked.
References OnSelectPattern().
void FillPattern::OnSelectPattern (wxMouseEvent & evt)
Used for single click in window, activated when button released.
This routine determines which bitmap was clicked, and notes it for future reference (when either it is double-clicked, or when the ok button is clicked).
Parameters:
evt wxMouseEvent Used to indicate the wxStaticBitmap in which the user clicked.
References setCurrentBitmap().
Referenced by OnChangePattern().
void FillPattern::setCurrentBitmap (int patternnum)
sets the current selected bitmap used a string resource name
Parameters:
patternnum int the number of an xrc resource which will be found and used for the current bitmap
References setCurrentBitmap().
void FillPattern::setCurrentBitmap (wxBitmap inbmp)
sets the current selected bitmap using a passed in bitmap
This routine takes a bitmap in, sets the default to it, and returns control to the caller.
Parameters:
inbmp wxBitmap a wxBitmap which will be used as the default choice for the fill pattern.
Referenced by Create(), OnCancel(), OnSelectPattern(), MainWin::OnToolFillPattern(), and setCurrentBitmap().
void FillPattern::setCurrentBitmap (wxString resName)
sets the current selected bitmap used a string resource name
Parameters:
resName wxString the name of an xrc resource which will be found and used for the current bitmap
References setCurrentBitmap().
Member Data Documentation
wxBitmap FillPattern::prevbmp [protected]
A holder to the previous bitmap pattern. Useful for the dialog which comes up, and reverts on cancellation
Referenced by Create(), and OnCancel().
The documentation for this class was generated from the following files:
FillPattern.h
FillPattern.cpp