AutoREALM: AutoRealmApp Class Reference
AutoRealmApp Class Reference
Main driver for the whole application.
#include <AutoRealmApp.h>
Public Member Functions
virtual bool OnInit ()
Startup routines for the whole application.
Protected Attributes
MainWin * mainwin
wxLocale locale
Detailed Description
Main driver for the whole application.
Derived from wxApp, this class is the main driver for the entire application. It will be responsible for startup, shutdown, and everything in between.
Todo:
Enable dockable toolbars in main window
Create and add custom controls to frmCTManager. Upper grid was labelled a "TDrawGrid", and lower grid was labelled "TStringGrid"
Populate comboboxes, lists, drop down boxes
Fix spacing between controls
Add shortcut keys where possible to menus, labels, etc
Use cursors where possible (if possible to do so in cross platform manner). A deleted directory in ui-xrc (cursors) has them.
Port "Custom Print" dialog
wxLogTrace() all of Josh's work, as it needs to be done still.
Member Function Documentation
bool AutoRealmApp::OnInit () [virtual]
Startup routines for the whole application.
Member method from wxApp, overridden for AutoRealmApp, and used to get the application initialization completed. No parameters
References InitActionsHandler(), InitAutoNameHandler(), InitCursorsHandler(), InitFillHandler(), InitInfoHandler(), InitMainHandler(), InitMenusHandler(), InitOverlayColorsHandler(), InitOverlayIconsHandler(), InitPushPinHandler(), InitSettingsHandler(), InitSplashHandler(), locale, and mainwin.
Member Data Documentation
wxLocale AutoRealmApp::locale [protected]
Used to make sure i18n functions are properly available, to make for nicer application to maintain
Referenced by OnInit().
MainWin* AutoRealmApp::mainwin [protected]
This is the main window for the application. It does not use std::auto_ptr for pointer management as this causes a runtime crash at exit (as both wxWidgets and std::auto_ptr try to delete the same memory).
Referenced by OnInit().
The documentation for this class was generated from the following files:
AutoRealmApp.h
AutoRealmApp.cpp