AutoREALM: DrawPrimitive.cpp File Reference
DrawPrimitive.cpp File Reference
#include <stdexcept>
#include <cmath>
#include "DrawPrimitive.h"
#include "LinePrimitive.h"
#include "CurvePrimitive.h"
#include "PolyLinePrimitive.h"
#include "PolyCurvePrimitive.h"
#include "MapObject.h"
#include "LocalizedStrings.h"
#include "generic_library.h"
#include "SettingsDlg.h"
#include "matrixmath.h"
#include "geometry.h"
Functions
void StartNewHandleDraw ()
bool CombineObjects_Realloc_Match (int n1, int n2, VPoints newpoints, int &newcount, VPoints first, int s1, VPoints second, int s2, DrawPrimitive o1, DrawPrimitive o2)
void CombineObjects_Realloc (VPoints &newpoints, int &newcount, VPoints first, int s1, VPoints second, int s2, DrawPrimitive o1, DrawPrimitive o2)
DrawPrimitive * CombineObjects (DrawPrimitive o1, DrawPrimitive o2)
DrawPrimitive * ConvertObject_DoubleDecompose (DrawPrimitive obj, wxString newtype)
DrawPrimitive * ConvertObject (DrawPrimitive obj, wxString newtype)
Detailed Description
Function Documentation
DrawPrimitive* CombineObjects (DrawPrimitive o1, DrawPrimitive o2)
Todo:
This section might be buggy. After all, we don't know what will happen with the ComputeExtent call, not really. Verify it works.
References wxToStd().
Referenced by ConvertObject_DoubleDecompose().
DrawPrimitive* ConvertObject_DoubleDecompose (DrawPrimitive obj, wxString newtype)
Todo:
Result.Destroy;
Todo:
polyobj.Destroy;
References CombineObjects().