AutoREALM: DrawLines.cpp File Reference
DrawLines.cpp File Reference
#include <cmath>
#include <algorithm>
#include "generic_library.h"
#include "rand.h"
#include "DrawLines.h"
#include "LinePoints.h"
#include "geometry.h"
Classes
struct GlyphData
struct EndPointData
struct RandomData
Functions
void DrawDot (TLineContinue &ldr, int x, int y)
Draws a dot on the canvas.
void correctperpendicular (arRealPoint &p)
: Used in getting lines perpendicular to the main line for drawing glyph/line tips.
void DitherLineDDAProc (int x, int y, TLineContinue *ldr)
DDA routine called by Window's LineDDA procedure. Called by normal dash-dot type lines.
void LineTipDDAProc (int x, int y, TLineContinue *ldr)
DDA routine called by Window's LineDDA procedure. Called for drawing symbols at line tips.
void DrawLineTip (coord x1, coord y1, coord x2, coord y2, int kind, wxDC &canvas)
StyleAttrib CleanedLineStyle (StyleAttrib style)
void Marquis (wxDC &canvas, int x1, int y1, int x2, int y2)
Draws dashed line surrounding selected area Caller must set the Canvas pen mode and color (usually pmNotXor if you want to draw the actual color you've selected into the Pen).
int RndSeed (int &seed, const int max)
Random number generator.
int GetNumberLineStyles ()
Returns total line styles available.
int GetNumberLineEndStyles ()
Returns total line end styles available.
int FixedRandom (int n)
Returns the nth fixed "random" number in the RandTable.
void CaligraphyDDAProc (int x, int y, TLineContinue *ldr)
: DDA routine called by Window's LineDDA procedure. Called by caligraphy type lines.
void RandomDDAProc (int x, int y, TLineContinue *ldr)
DDA routine called by Window's LineDDA procedure. Called by random type lines.
void GlyphLineDDAProc (int x, int y, TLineContinue *ldr)
DDA routine called by Window's LineDDA procedure. Called by glyph type lines (ones with symbols in them).
void DoFractal (int depth, coord x1, coord y1, coord x2, coord y2, double rfact, arRealRect &b)
void GetFractalBox (coord x1, coord y1, coord x2, coord y2, double rfact, arRealRect &b)
void FractalSetSeed (int n)
TLineContinue GetLineStyleStart (StyleAttrib style)
void DrawLineContinue (wxDC &canvas, coord x1, coord y1, coord x2, coord y2, TLineContinue &cont)
Draws a line (x1,y1)-(x2,y2).
VPoints GetLineEnd (TLineContinue &cont, int &count)
Ends a line.
void DrawLineStyle (wxDC &canvas, int x1, int y1, int x2, int y2, StyleAttrib style)
Routine for drawing a single line segment without the fuss & muss.
void doBezier (int depth, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, wxDC &canvas, TLineContinue &cont)
void DrawBezier (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, TLineContinue &cont)
Draws a bezier curve.
void doFractalBezier (int depth, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, wxDC &canvas, TLineContinue &cont)
void DrawFractalBezier (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, TLineContinue &cont)
Draws fractal bezier curve.
void DrawArc (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, TLineContinue &cont)
void GetArcCenter (arRealPoint p1, arRealPoint p2, arRealPoint p3, coord &x1, coord &y1)
void doGetBezierBox (int depth, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, arRealRect &b)
void GetBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, arRealRect &b)
Gets a bounding box for a bezier curve.
void doGetFractalBezierBox (int depth, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, arRealRect &b)
void GetFractalBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, arRealRect &b)
Gets a bounding box for a fractal bezier curve.
int GetLineThickness (StyleAttrib style)
Get width of line style.
bool IsAComplexLine (StyleAttrib style)
Figure out if the line style requires a substantial amount of time to draw or not.
StyleAttrib InvertLineStyle (StyleAttrib style)
Flips a line's style.
bool IsLineStyleInverted (StyleAttrib style)
Returns true if the line style is to be inverted (used for "reversing" lines)
void doFractalLine (int depth, coord x1, coord y1, coord x2, coord y2, double rfact, TLineContinue &cont, wxDC &canvas)
void FractalLine (wxDC &canvas, coord x1, coord y1, coord x2, coord y2, double rfact, TLineContinue &cont)
Draws a fractal line; rfact is the "width".
Variables
const int AllocationGrowth = 200
const int fractal_depth = 16
const unsigned int dashdot [number_dithered_styles]
const unsigned int GlyphBits [531]
const EndPointData LineEnds [number_lineends]
const GlyphData Glyph [number_glyph_styles]
const RandomData RandomDot [number_random_styles]
const int RandTableLen = 256
int RandTable [RandTableLen]
int LastSeed = -1
Detailed Description
This file contains many drawing functions used to actually place things on-screen.
Function Documentation
void CaligraphyDDAProc (int x, int y, TLineContinue * ldr)
: DDA routine called by Window's LineDDA procedure. Called by caligraphy type lines.
We draw a broad stroke for each dot, centered around the real line.
Referenced by DrawLineContinue().
StyleAttrib CleanedLineStyle (StyleAttrib style)
Returns line style with any flags removed from the bitmask
References StyleAttrib::bits.
Referenced by GetLineStyleStart().
void correctperpendicular (arRealPoint & p)
: Used in getting lines perpendicular to the main line for drawing glyph/line tips.
Make sure the length of the line we create is in the direction of the perpendicular, but make the sum of the number of pixels in the x and y direction equals 16 (or 1/2 our maximum width).
Without this property, our glyph line will not always be centered around the correct point.
The way to ensure this is to force the longest axis of the line (0,0)-(px,py) equal to 1 (since we're still dealing with unit coordinates), and scale the other axis accordingly.
Referenced by DrawLineContinue(), and DrawLineTip().
void DitherLineDDAProc (int x, int y, TLineContinue * ldr)
DDA routine called by Window's LineDDA procedure. Called by normal dash-dot type lines.
Rotates the bitmask over by one bit each time it is called so the bits are sequentially applied.
Bug:
On 64 bit platforms, this one may be a problem. Basically, an assumption is made here that an int is 32 bits. Need to find a way to restrict to that 32 bits, and make sure it's no smaller than 32 bits, either.
References DrawDot().
Referenced by DrawLineContinue(), GlyphLineDDAProc(), and LineTipDDAProc().
void DrawBezier (wxDC & canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, TLineContinue & cont)
Draws a bezier curve.
If there is more resolution desired, split the curve, and recurse. The curve is split using a simple and effective equality: De Castigilu's Algorithm):
  Conceptual
  (coordinates)
   p1
     > q1
   p2    > r1
     > q2    > s1
   p3    > r2
     > q3
   p4
p1..p4 are the points of the original bezier curve. Each parent coord. on the tree above is the average of the two coords below. The point s1 is the split point, and the curves <p1 q1="" r1="" s1>="">, and <p4 q3="" r2="" s1>=""> are the two resulting Bezier curves. The combination of the two curves resulting from splitting reproduces the original (disregarding roundoff errors).
References GetLineEnd().
void DrawFractalBezier (wxDC & canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, TLineContinue & cont)
Draws fractal bezier curve.
Assumes that FractalSetSeed has been called.
void DrawLineContinue (wxDC & canvas, coord x1, coord y1, coord x2, coord y2, TLineContinue & cont)
Draws a line (x1,y1)-(x2,y2).
Requires the continue record be filled out before hand. That is, this routine does no initialization or cleanup, and doesn't handle the line tips. It is called multiple times, though for polylines.
Todo:
find a way to tell if this is going to a printer or not.
References angle(), StyleAttrib::bits, CaligraphyDDAProc(), correctperpendicular(), DitherLineDDAProc(), DrawLineTip(), StyleAttrib::FullStyle, GetLineThickness(), GlyphLineDDAProc(), LinePoints(), RandomDDAProc(), round(), TFullStyle::SThickness, unitperpendicular(), and visiblewithin().
Referenced by DrawEnclosedFigure(), and DrawLineStyle().
void DrawLineStyle (wxDC & canvas, int x1, int y1, int x2, int y2, StyleAttrib style)
Routine for drawing a single line segment without the fuss & muss.
For polylines, you can't call this, you need to do LineStart, Continue, End.
References DrawLineContinue(), GetLineEnd(), and GetLineStyleStart().
void DrawLineTip (coord x1, coord y1, coord x2, coord y2, int kind, wxDC & canvas)
Draws a symbol at the tip of a line
References correctperpendicular(), LinePoints(), LineTipDDAProc(), and unitvector().
Referenced by DrawLineContinue(), and GetLineEnd().
int FixedRandom (int n)
Returns the nth fixed "random" number in the RandTable.
After RandTable is filled with random numbers, the fractal algorithms use it to get predictable random numbers from the table. We can't use real random numbers here because the total numbers required changes depending on our zoom level. Since the fractals are generated recursively, it would mean that without doing this the shape of our fractal lines would change at each zoom level. This is unacceptable.
Todo:
The original code used low(RandTable) and High(RandTable). Technically, this allows for an array with different starting/ending values than 0/256, as is required high. Since this is different, we may have a bug, or we may not. It's worth verifying one way or the other, though.
void FractalLine (wxDC & canvas, coord x1, coord y1, coord x2, coord y2, double rfact, TLineContinue & cont)
Draws a fractal line; rfact is the "width".
Assumes that FractalSetSeed has been called.
References GetLineEnd().
void FractalSetSeed (int n)
Fills the RandTable: future calls to fractal routines will have this "shape".
References getRndNumber(), and setRndSeed().
void GetBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, arRealRect & b)
Gets a bounding box for a bezier curve.
Used in calculation of invalid regions
void GetFractalBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, arRealRect & b)
Gets a bounding box for a fractal bezier curve.
Used in calculation of invalidation regions
void GetFractalBox (coord x1, coord y1, coord x2, coord y2, double rfact, arRealRect & b)
Purpose: Determine the bounding box for a fractal.
Notes: Used in invalidating regions to find out the rectangle surrounding the fractal.
VPoints GetLineEnd (TLineContinue & cont, int & count)
Ends a line.
If a SEGMENT_STYLE line, we return the list of segments.
References StyleAttrib::bits, and DrawLineTip().
Referenced by DrawBezier(), DrawEnclosedFigure(), DrawLineStyle(), and FractalLine().
TLineContinue GetLineStyleStart (StyleAttrib style)
Initializes the TLineContinue struct for the beginning of a line.
References CleanedLineStyle(), and IsLineStyleInverted().
Referenced by DrawEnclosedFigure(), and DrawLineStyle().
int GetLineThickness (StyleAttrib style)
Get width of line style.
Called by drawing primitives if the "Quick Draw" mode is set to reduce drawing time.
Could also be used to shrink the invalidation regions slightly. When the canvas is manipulated, the area affected is invalidated plus a several pixel border to make sure changing line styles also get invalidated. If we were "smarter", we could calculate exactly how wide that border would need to be. Needless to say, it's easier just to slightly inflate the invalidation region and suffer the minor (if any) cost in repaint time.
Referenced by DrawLineContinue().
int GetNumberLineEndStyles ()
Returns total line end styles available.
This is essentially a fixed number since the user can't add their own styles. It's written as a function, because if we do let the user add styles, they'd have to go at the bottom of the list, and we'd increment our return value by the number of user styles.
int GetNumberLineStyles ()
Returns total line styles available.
This is essentially a fixed number since the user can't add their own styles. It's written as a function, because if we do let the user add styles, they'd have to go at the bottom of the list, and we'd increment our return value by the number of user styles.
void GlyphLineDDAProc (int x, int y, TLineContinue * ldr)
DDA routine called by Window's LineDDA procedure. Called by glyph type lines (ones with symbols in them).
Draws many lines perpendicular to the original line, straddling it. The individual lines are dot-dash style lines, but we set the dot-dash mask to the appropriate row of our glyph. i.e.
    + + + +<Individual glyph slices drawn perp. to the line
    + + + +
   -+-+-+-+---------------------------------------------- line
    + + + +
    + + + +
This isn't the best way to do this. For one, it's pretty darn slow. For two, it leaves noticible gaps in the lines when rotated: 90 degree lines are much more compact than 45 degree lines. I explored several better options for glyph lines, but they all suffered when it came to applying the pattern to a fractal line or a curve. Specifically, joining corners when faced with zillions of line stretches one pixel long (and frequently non tangential) made representing the glyph lines as paths or polygons pretty darn inconvient. Doing that, they would have to be sliced into thin sections, and reasonably joined when the intersection angle of the lines could be pretty large. So although not the best in terms of appearance of simple straight lines, these "bitmap" lines are a good all-around compromise.
References DitherLineDDAProc(), and LinePoints().
Referenced by DrawLineContinue().
bool IsAComplexLine (StyleAttrib style)
Figure out if the line style requires a substantial amount of time to draw or not.
Called by drawing primitives if the "Quick Draw" mode is set to reduce drawing time.
void LineTipDDAProc (int x, int y, TLineContinue * ldr)
DDA routine called by Window's LineDDA procedure. Called for drawing symbols at line tips.
See GlyphDDAProc for reasoning--this routine is very similar.
References DitherLineDDAProc(), and LinePoints().
Referenced by DrawLineTip().
void Marquis (wxDC & canvas, int x1, int y1, int x2, int y2)
Draws dashed line surrounding selected area Caller must set the Canvas pen mode and color (usually pmNotXor if you want to draw the actual color you've selected into the Pen).
Todo:
get mainform background : Original code:
void RandomDDAProc (int x, int y, TLineContinue * ldr)
DDA routine called by Window's LineDDA procedure. Called by random type lines.
The dy variable is used to control the "fuzziness"
References DrawDot(), and RndSeed().
Referenced by DrawLineContinue().
int RndSeed (int & seed, const int max)
Random number generator.
Used to give reliable random numbers that don't change, even if new platforms/toolkits become available. While this function should, probably, be replaced, it will not be at this time, at the least.
Referenced by RandomDDAProc().
Variable Documentation
const unsigned int dashdot[number_dithered_styles]
Initial value:
{
    0x55555555,
    0xFFC3C3FF,
    0xFF1E3CFF,
    0xFFF3FFF3,
    0xF99F33CC,
    0x0F0F0F0F,
    0x11111111,
    0x10101010,
    0xFFFFF924
}
const EndPointData LineEnds[number_lineends]
Initial value:
{
    {0,  0,  0,    0},
    {16, 6,  382,  0},
    {16, 6,  388,  0},
    {16, 10, 475,  0},
    {16, 10, 394,  0},
    {16, 10, 413,  3},
    {16, 6,  407,  5},
    {16, 6,  495,  0},
    {16, 10, 485,  0},
    {16, 1,  404,  0},
    {16, 1,  405,  0},
    {16, 1,  406,  0},
    {16, 5,  423,  4},
    {16, 5,  428,  0},
    {16, 7,  433,  3},
    {16, 7,  440,  3},
    {16, 7,  447,  3},
    {16, 7,  454,  3},
    {16, 7,  461,  3},
    {16, 7,  468,  3}
}