AutoREALM: DrawLines.h File Reference
DrawLines.h File Reference
#include "globals.h"
#include "types.h"
Classes
struct TFullStyle
struct StyleAttrib
struct TLineContinue
Functions
void Marquis (wxDC &canvas, int x1, int y1, int x2, int y2)
Draws dashed line surrounding selected area Caller must set the Canvas pen mode and color (usually pmNotXor if you want to draw the actual color you've selected into the Pen).
void GetFractalBox (coord x1, coord y1, coord x2, coord y2, double rfact, arRealRect &b)
void FractalLine (wxDC &canvas, coord x1, coord y1, coord x2, coord y2, double rfact, TLineContinue &cont)
Draws a fractal line; rfact is the "width".
void FractalSetSeed (int n)
int GetNumberLineStyles ()
Returns total line styles available.
int GetNumberLineEndStyles ()
Returns total line end styles available.
TLineContinue GetLineStyleStart (StyleAttrib style)
void DrawLineContinue (wxDC &canvas, coord x1, coord y1, coord x2, coord y2, TLineContinue &cont)
Draws a line (x1,y1)-(x2,y2).
VPoints GetLineEnd (TLineContinue &cont, int &count)
Ends a line.
void DrawLineStyle (wxDC &canvas, int x1, int y1, int x2, int y2, StyleAttrib style)
Routine for drawing a single line segment without the fuss & muss.
void DrawBezier (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, TLineContinue &cont)
Draws a bezier curve.
void DrawFractalBezier (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, TLineContinue &cont)
Draws fractal bezier curve.
void DrawArc (wxDC &canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, TLineContinue &cont)
void GetArcCenter (arRealPoint p1, arRealPoint p2, arRealPoint p3, coord &x1, coord &y1)
void GetBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, arRealRect &b)
Gets a bounding box for a bezier curve.
void GetFractalBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, arRealRect &b)
Gets a bounding box for a fractal bezier curve.
int GetLineThickness (StyleAttrib style)
Get width of line style.
bool IsAComplexLine (StyleAttrib style)
Figure out if the line style requires a substantial amount of time to draw or not.
int FixedRandom (int n)
Returns the nth fixed "random" number in the RandTable.
StyleAttrib InvertLineStyle (StyleAttrib style)
Flips a line's style.
bool IsLineStyleInverted (StyleAttrib style)
Returns true if the line style is to be inverted (used for "reversing" lines)
Variables
const StyleAttrib SEGMENT_STYLE = {0,{0xFFFFFFFF, -1, 0}}
const int MaxRand = 256*1024
const int number_thick_styles = 6
const int number_dithered_styles = 9
const int number_glyph_styles = 41
const int number_caligraphy_styles = 12
const int number_random_styles = 60
const int number_numeric_thickness_styles = 1
const int number_lineends = 20
const int start_thick_style = 1
const int start_dithered_style = start_thick_style + number_thick_styles
const int start_glyph_style = start_dithered_style + number_dithered_styles
const int start_caligraphy_style = start_glyph_style + number_glyph_styles
const int start_random_style = start_caligraphy_style + number_caligraphy_styles
const int start_numeric_thickness_style = start_random_style + number_random_styles
Detailed Description
Function Documentation
void DrawBezier (wxDC & canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, TLineContinue & cont)
Draws a bezier curve.
If there is more resolution desired, split the curve, and recurse. The curve is split using a simple and effective equality: De Castigilu's Algorithm):
  Conceptual
  (coordinates)
   p1
     > q1
   p2    > r1
     > q2    > s1
   p3    > r2
     > q3
   p4
p1..p4 are the points of the original bezier curve. Each parent coord. on the tree above is the average of the two coords below. The point s1 is the split point, and the curves <p1 q1="" r1="" s1>="">, and <p4 q3="" r2="" s1>=""> are the two resulting Bezier curves. The combination of the two curves resulting from splitting reproduces the original (disregarding roundoff errors).
References GetLineEnd().
void DrawFractalBezier (wxDC & canvas, arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, TLineContinue & cont)
Draws fractal bezier curve.
Assumes that FractalSetSeed has been called.
void DrawLineContinue (wxDC & canvas, coord x1, coord y1, coord x2, coord y2, TLineContinue & cont)
Draws a line (x1,y1)-(x2,y2).
Requires the continue record be filled out before hand. That is, this routine does no initialization or cleanup, and doesn't handle the line tips. It is called multiple times, though for polylines.
Todo:
find a way to tell if this is going to a printer or not.
References angle(), StyleAttrib::bits, CaligraphyDDAProc(), correctperpendicular(), DitherLineDDAProc(), DrawLineTip(), StyleAttrib::FullStyle, GetLineThickness(), GlyphLineDDAProc(), LinePoints(), RandomDDAProc(), round(), TFullStyle::SThickness, unitperpendicular(), and visiblewithin().
Referenced by DrawEnclosedFigure(), and DrawLineStyle().
void DrawLineStyle (wxDC & canvas, int x1, int y1, int x2, int y2, StyleAttrib style)
Routine for drawing a single line segment without the fuss & muss.
For polylines, you can't call this, you need to do LineStart, Continue, End.
References DrawLineContinue(), GetLineEnd(), and GetLineStyleStart().
int FixedRandom (int n)
Returns the nth fixed "random" number in the RandTable.
After RandTable is filled with random numbers, the fractal algorithms use it to get predictable random numbers from the table. We can't use real random numbers here because the total numbers required changes depending on our zoom level. Since the fractals are generated recursively, it would mean that without doing this the shape of our fractal lines would change at each zoom level. This is unacceptable.
Todo:
The original code used low(RandTable) and High(RandTable). Technically, this allows for an array with different starting/ending values than 0/256, as is required high. Since this is different, we may have a bug, or we may not. It's worth verifying one way or the other, though.
void FractalLine (wxDC & canvas, coord x1, coord y1, coord x2, coord y2, double rfact, TLineContinue & cont)
Draws a fractal line; rfact is the "width".
Assumes that FractalSetSeed has been called.
References GetLineEnd().
void FractalSetSeed (int n)
Fills the RandTable: future calls to fractal routines will have this "shape".
References getRndNumber(), and setRndSeed().
void GetBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, arRealRect & b)
Gets a bounding box for a bezier curve.
Used in calculation of invalid regions
void GetFractalBezierBox (arRealPoint p1, arRealPoint p2, arRealPoint p3, arRealPoint p4, double rfact, arRealRect & b)
Gets a bounding box for a fractal bezier curve.
Used in calculation of invalidation regions
void GetFractalBox (coord x1, coord y1, coord x2, coord y2, double rfact, arRealRect & b)
Purpose: Determine the bounding box for a fractal.
Notes: Used in invalidating regions to find out the rectangle surrounding the fractal.
VPoints GetLineEnd (TLineContinue & cont, int & count)
Ends a line.
If a SEGMENT_STYLE line, we return the list of segments.
References StyleAttrib::bits, and DrawLineTip().
Referenced by DrawBezier(), DrawEnclosedFigure(), DrawLineStyle(), and FractalLine().
TLineContinue GetLineStyleStart (StyleAttrib style)
Initializes the TLineContinue struct for the beginning of a line.
References CleanedLineStyle(), and IsLineStyleInverted().
Referenced by DrawEnclosedFigure(), and DrawLineStyle().
int GetLineThickness (StyleAttrib style)
Get width of line style.
Called by drawing primitives if the "Quick Draw" mode is set to reduce drawing time.
Could also be used to shrink the invalidation regions slightly. When the canvas is manipulated, the area affected is invalidated plus a several pixel border to make sure changing line styles also get invalidated. If we were "smarter", we could calculate exactly how wide that border would need to be. Needless to say, it's easier just to slightly inflate the invalidation region and suffer the minor (if any) cost in repaint time.
Referenced by DrawLineContinue().
int GetNumberLineEndStyles ()
Returns total line end styles available.
This is essentially a fixed number since the user can't add their own styles. It's written as a function, because if we do let the user add styles, they'd have to go at the bottom of the list, and we'd increment our return value by the number of user styles.
int GetNumberLineStyles ()
Returns total line styles available.
This is essentially a fixed number since the user can't add their own styles. It's written as a function, because if we do let the user add styles, they'd have to go at the bottom of the list, and we'd increment our return value by the number of user styles.
bool IsAComplexLine (StyleAttrib style)
Figure out if the line style requires a substantial amount of time to draw or not.
Called by drawing primitives if the "Quick Draw" mode is set to reduce drawing time.
void Marquis (wxDC & canvas, int x1, int y1, int x2, int y2)
Draws dashed line surrounding selected area Caller must set the Canvas pen mode and color (usually pmNotXor if you want to draw the actual color you've selected into the Pen).
Todo:
get mainform background : Original code: