AutoREALM: generic_library.cpp File Reference
generic_library.cpp File Reference
#include <math.h>
#include <wx/strconv.h>
#include "generic_library.h"
Functions
double round (double val, int decimals)
Round a given number to a given number of decimal places.
std::string wxToStd (const wxString &str)
Detailed Description
Function Documentation
double round (double val, int decimals = 0)
Round a given number to a given number of decimal places.
Parameters:
val The number to be rounded to
decimals the number of decimal places to round to. 2 would be hundredths/pennies.
Returns:
The number rounded to the specified number of decimal places.
Referenced by DrawEnclosedFigure(), DrawLineContinue(), ViewPoint::GetZoomPercent(), and ViewPoint::SetCoordinateRect().
std::string wxToStd (const wxString & str)
This takes a wxString, and converts it into a std::string. I would make this into a global macro, but I don't want to include wx/strconv.h in every single file.
Parameters:
str The wxString to be converted
Returns:
a std::string built from the passed in string
Referenced by CombineObjects().