AutoREALM: geometry.h File Reference
geometry.h File Reference
#include <wx/gdicmn.h>
#include "globals.h"
#include "types.h"
Enumerations
enum IntersectType {
NoIntersect = 0, IntersectOnLine, IntersectOffLine, IntersectOffLineBegin,
IntersectOffLineEnd
}
Indicates the result of an intersection test When a point/line is tested for intersection, one of these values is the result.
Functions
void encompass (arRealRect &r, const arRealPoint &p)
Extend the wxRect to encompass the point.
void encompass (arRealRect &r, double x, double y)
Extend the wxRect to encompass the point.
double distance (double x1, double y1, double x2, double y2)
Returns the distance between the two points.
double distance (const arRealPoint &p1, const arRealPoint &p2)
Returns the distance between the two points.
double distance2 (double x1, double y1, double x2, double y2)
returns the square of the distance between the two points. It's faster than distance for figuring out which one is closer.
double distance2 (const arRealPoint &p1, const arRealPoint &p2)
returns the square of the distance between the two points. It's faster than distance for figuring out which one is closer.
double angle (double x1, double y1, double x2, double y2)
Returns the angle?
double angle (const arRealPoint &p1, const arRealPoint &p2)
Returns the angle?
arRealPoint unitvector (double x1, double y1, double x2, double y2)
Returns the unit vector corresponding to the two points.
arRealPoint unitvector (const arRealPoint &p1, const arRealPoint &p2)
Returns the unit vector corresponding to the two points.
arRealPoint unitperpendicular (double x1, double y1, double x2, double y2)
Returns a unit vector perpendicular to the vector represented by the two points.
arRealPoint unitperpendicular (const arRealPoint &p1, const arRealPoint &p2)
Returns a unit vector perpendicular to the vector represented by the two points.
arRealPoint midpoint (double x1, double y1, double x2, double y2)
Returns the midpoint of the line segment described by two points.
arRealPoint midpoint (const arRealPoint &p1, const arRealPoint &p2)
Returns the midpoint of the line segment described by two points.
bool visiblewithin (const arRealRect &vp, const arRealRect &r)
Returns true if any part of r is inside (or on) vp (viewport)
bool visiblewithin (const wxRect &vp, const wxRect &r)
Returns true if any part of r is inside (or on) vp (viewport)
double distancetosegment (const arRealPoint &p, const arRealPoint &ep1, const arRealPoint &ep2)
returns the distance from the point to the segment
bool intersection (const arRealPoint &p1, const arRealPoint &p2, const arRealPoint &p3, const arRealPoint &p4)
do the lines intersect?
IntersectType intersection (const arRealPoint &p1, const arRealPoint &p2, const arRealPoint &p3, const arRealPoint &p4, arRealPoint &ip)
In what way do the line segments intersect?
bool CropLineOutsideRect (const arRealPoint &p1, const arRealPoint &p2, const arRealRect &r)
Clips the portion of the line segment outside of the arRealRect.
bool ExtendLineToRect (arRealPoint &p1, arRealPoint &p2, const arRealRect &r)
Extends the line segment until it intersects with the arRealRect.
bool PointInPolygon (const arRealPoint &p, const arRealRect &polyextent, const VPoints &poly)
Is this point in the polygon?
bool NearestIntersection (const std::vector< arRealPoint > &segments, const std::vector< int > numsegments, arRealPoint &isect)
Locates the closest intersection in the polygon to the point.
arRealPoint avepoints (const arRealPoint &a, const arRealPoint &b)
Averages two map coordinate points.
bool ptInRealRectDelta (const arRealRect &r, const arRealPoint &p, const coord delta)
Checks to see if a point is in a arRealRect with a delta.
double distanceToSegment (const arRealPoint &p, const arRealPoint &p1, const arRealPoint &p2)
IntersectType intersectLine (const arRealPoint &p1, const arRealPoint &p2, const arRealPoint &p3, const arRealPoint &p4, arRealPoint &isect)
bool CropLineOutsideRect (arRealPoint &p1, arRealPoint &p2, const arRealRect &r)
bool PointInPolygon (const arRealPoint &p, const arRealRect &polyextent, const VPoints &poly, int polycount)
bool NearestIntersection (const VPoints &segments, int *numsegments, arRealPoint &isect)
arRealRect MakeCoordRect (coord left, coord top, coord right, coord bottom)
void CorrectCoordRect (arRealRect &r)
Detailed Description
Function Documentation
double angle (double x1, double y1, double x2, double y2)
Returns the angle?
Todo:
Verify
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The angle of the points
Ok, there's these two points. They are colinear (as any two paints must be). This function finds the slope of the line as an angle between that line and the positive X axis. Then it returns that angle measured in Radians
Parameters:
(x1,y1),(x2,y2) - the end points of a line segment
Returns:
the angle the line segment makes with the positive x axis
Referenced by angle(), DrawLineContinue(), and GetAverageAngle().
double angle (const arRealPoint & p1, const arRealPoint & p2)
Returns the angle?
Todo:
Verify
Parameters:
p1 The first point
p2 The second point
Returns:
The angle of the points
Parameters:
p1,p2 - the endpoints of a line segment
Returns:
the angle the line segment makes with the positive x axis
References angle().
bool CropLineOutsideRect (const arRealPoint & p1, const arRealPoint & p2, const arRealRect & r)
Clips the portion of the line segment outside of the arRealRect.
Parameters:
p1 The beginning point of the line
p2 The ending point of the line
r The clipping rectangle
Returns:
Returns true if any portion of the line remains. Returns false if the entire line was outside of the rect
bool CropLineOutsideRect (arRealPoint & p1, arRealPoint & p2, const arRealRect & r)
Parameters:
p1,p2 - the endpoints of the line segment
r - the rectangle to clip the line segment to
Returns:
true if the line segment was altered, else false
References intersection(), and visiblewithin().
double distance (const arRealPoint & p1, const arRealPoint & p2)
Returns the distance between the two points.
Parameters:
p1 The first point
p2 The second point
Returns:
The distance between the two points
Parameters:
p1 - point 1
p2 - point 2
Returns:
distance between the two points
References distance2().
Referenced by distancetosegment(), unitperpendicular(), and unitvector().
double distance (double x1, double y1, double x2, double y2)
Returns the distance between the two points.
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The distance between the two points
Parameters:
(x1,y1) - point 1
(x2,y2) - point 2
Returns:
the distance between the two points
References distance2().
double distance2 (double x1, double y1, double x2, double y2)
returns the square of the distance between the two points. It's faster than distance for figuring out which one is closer.
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The square of the distance between the two points
This function returns the square of the distance. If all you're doing is comparing the distances between points, this function is faster than distarce() because it doesn't compute the square root
Parameters:
(x1,y1) - point 1
(x2,y2) - point 2
Returns:
square of the distance between the two points
Referenced by distance(), distance2(), and NearestPoint().
double distance2 (const arRealPoint & p1, const arRealPoint & p2)
returns the square of the distance between the two points. It's faster than distance for figuring out which one is closer.
Parameters:
p1 The first point
p2 The second point
Returns:
The square of the distance between the two points
Parameters:
p1 - point 1
p2 - point 2
Returns:
square of the distance between the two points
References distance2().
double distancetosegment (const arRealPoint & p, const arRealPoint & ep1, const arRealPoint & ep2)
returns the distance from the point to the segment
Parameters:
p The point which is not on the segment
ep1 The begin point of the segment
ep2 The end point of the segment
Returns:
The distance from the point to the segment
Parameters:
p - point to measure from
ep1,ep2 - end points of the line segment
Returns:
distance from the point to the line segment
References distance().
void encompass (arRealRect & r, double x, double y)
Extend the wxRect to encompass the point.
Todo:
possibly make this a member function of arRealRect?
Parameters:
r A arRealRect to be extended
x The x coordinate of the point to be added to the arRealRect
y The y coordinate of the point to be added to the arRealRect
References encompass().
void encompass (arRealRect & r, const arRealPoint & p)
Extend the wxRect to encompass the point.
Todo:
possibly make this a member function of arRealRect?
Parameters:
r A arRealRect to be extended
p a arRealPoint which is to be put into the arRealRect
Enlarges the arRealRect to include the point p
Referenced by encompass().
bool ExtendLineToRect (arRealPoint & p1, arRealPoint & p2, const arRealRect & r)
Extends the line segment until it intersects with the arRealRect.
Parameters:
p1 The beginning point of the line
p2 The ending point of the line
r The rectangle we wish to have (p1,p2) intersect with
Returns:
true if the line was changed, else false
Parameters:
p1,p2 - the endpoints of the line segment
r - the rectangle the line segment is extended to
Returns:
true if some extending was done
References intersection().
bool intersection (const arRealPoint & p1, const arRealPoint & p2, const arRealPoint & p3, const arRealPoint & p4)
do the lines intersect?
Parameters:
p1 beginning point of line 1
p2 ending point of line 1
p3 beginning point of line 2
p4 ending point of line 2
Returns:
true if the lines intersect, false otherwise
Compares the slope of line p1,p2 and p3,p4 to see if they intersect. They intersect if the slopes are not equal
Parameters:
p1,p2 - two points on line 1
p3,p4 - two points on line 2
Returns:
true if the lines are not parallel
Referenced by CropLineOutsideRect(), ExtendLineToRect(), and PointInPolygon().
IntersectType intersection (const arRealPoint & p1, const arRealPoint & p2, const arRealPoint & p3, const arRealPoint & p4, arRealPoint & ip)
In what way do the line segments intersect?
Parameters:
p1 beginning point of line 1
p2 ending point of line 1
p3 beginning point of line 2
p4 ending point of line 2
ip (output) The location of the intersection, if there is one
Returns:
The type of intersection which was found
Finds the point of intersection (if one exists) and returns whether the point of intersection is on or off of the segments
Parameters:
p1,p2 - endpoints of one line segment
p3,p4 - endpoints of the other line segment
ip - the point of intersection
Returns:
the type of intersection
IntersectType intersectLine (const arRealPoint & p1, const arRealPoint & p2, const arRealPoint & p3, const arRealPoint & p4, arRealPoint & isect)
Returns true if the lines intersect; false if the lines are parallel
arRealPoint midpoint (double x1, double y1, double x2, double y2)
Returns the midpoint of the line segment described by two points.
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The midpoint of the line segment described by these two points
Parameters:
x1,y1 - one end point of the line segment
x2,y2 - the other point of the line segment
Returns:
the midpoint of the line segment
Referenced by midpoint().
arRealPoint midpoint (const arRealPoint & p1, const arRealPoint & p2)
Returns the midpoint of the line segment described by two points.
Parameters:
p1 The first point
p2 The second point
Returns:
The midpoint of the line segment described by these two points
Parameters:
p1,p2 - endpoints of the line segment
Returns:
the midpoint of the line segment
References midpoint().
bool NearestIntersection (const std::vector< arRealPoint > & segments, const std::vector< int > numsegments, arRealPoint & isect)
Locates the closest intersection in the polygon to the point.
Todo:
document numsegments vector
document what true/false means for the return value
Parameters:
segments the segments which make up the polygon
numsegments Unknown
isect (output)The nearest point of intersection to the polygon for the point
Returns:
true/false
bool PointInPolygon (const arRealPoint & p, const arRealRect & polyextent, const VPoints & poly, int polycount)
Returns if the point is inside the polygon. Uses the classic method of hit testing by making a horizontal ray from the point, and counting the intersections. An even count is outside, and odd count is inside.
Todo:
why 1000? what's the significance?
References intersection().
bool PointInPolygon (const arRealPoint & p, const arRealRect & polyextent, const VPoints & poly)
Is this point in the polygon?
Parameters:
p The point to be examined
polyextent The clipping rectangle of the polygon
poly The points which make up the polygon
Returns:
true if the point is in the polygon, false otherwise
Returns true if the point is in the polygon
Parameters:
p - the point to test
polyextent - a rectangle enclosing the polygon, used to short-circuit the test
poly - the points that make up the vertices of the polygon
What we do (after checking for the simple no cases), is create a line from p to a point we know is outside the polygon. Then we count how many times that line intersects with one of the sides of the polygon. If the count is even (including 0), then the point is outside of the polygon. If the count is odd, then the point is inside the polygon.
References intersection().
arRealPoint unitperpendicular (double x1, double y1, double x2, double y2)
Returns a unit vector perpendicular to the vector represented by the two points.
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The unit vector perpendicular to the vector represented by the two points
Ok, this is just the same as the unitvector, but perpendicular instead of parallel.
Parameters:
x1,y1 - one endpoint of a line segment
x2,y2 - the other endpoint of a line segment
Returns:
a point representing the unit perpendicular vector to the line segment
References distance().
Referenced by DrawLineContinue(), and unitperpendicular().
arRealPoint unitperpendicular (const arRealPoint & p1, const arRealPoint & p2)
Returns a unit vector perpendicular to the vector represented by the two points.
Parameters:
p1 The first point
p2 The second point
Returns:
The unit vector perpendicular to the vector represented by the two points
Parameters:
p1,p2 - a line segment representing the vector (p1 to p2)
Returns:
a point representing the unitperpendicular to that line segment
References unitperpendicular().
arRealPoint unitvector (const arRealPoint & p1, const arRealPoint & p2)
Returns the unit vector corresponding to the two points.
Parameters:
p1 The first point
p2 The second point
Returns:
The unit vector corresponding to the two points
Parameters:
p1,p2 - the endpoints of a line segment representing a vector
Returns:
the unit vector with the same directional component as the line segment
References unitvector().
arRealPoint unitvector (double x1, double y1, double x2, double y2)
Returns the unit vector corresponding to the two points.
Parameters:
x1 The x coordinate of the first point
y1 The y coordinate of the first point
x2 The x coordinate of the second point
y2 The y coordinate of the second point
Returns:
The unit vector corresponding to the two points
Ok, there's these two points. Together, they describe the direction and magnitude of a vector. Now this function returns a point representing the unit vector with the same directional component as the original vector.
Parameters:
(x1,y1),(x2,y2) - the end points of the line segment representing a vector
Returns:
the unit vector with the same directional component as the original vector
References distance().
Referenced by DrawLineTip(), and unitvector().
bool visiblewithin (const wxRect & vp, const wxRect & r)
Returns true if any part of r is inside (or on) vp (viewport)
Parameters:
vp The viewport which is being examined to see if r is visible from it
r The area we wish to know if any part of is visible from vp
Returns:
true if r is visible from vp, false if not
Parameters:
vp - view port
r - rectangle
Returns:
Is r visible within vp?
bool visiblewithin (const arRealRect & vp, const arRealRect & r)
Returns true if any part of r is inside (or on) vp (viewport)
Parameters:
vp The viewport which is being examined to see if r is visible from it
r The area we wish to know if any part of is visible from vp
Returns:
true if r is visible from vp, false if not
Parameters:
vp - view port
r - rectangle
Returns:
Is r visible within vp?
Referenced by CropLineOutsideRect(), and DrawLineContinue().