AutoREALM: LinePoints.h File Reference
LinePoints.h File Reference
#include <wx/dc.h>
#include <wx/gdicmn.h>
Functions
void LinePoints (int x0, int y0, int x1, int y1, void(*callback)(int, int, void *), void *data)
LinePoints - executes the callback function for each point to be drawn on the line.
Detailed Description
Function Documentation
void LinePoints (int x0, int y0, int x1, int y1, void(*)(int, int, void *) setPixel, void * data)
LinePoints - executes the callback function for each point to be drawn on the line.
Todo:
Optimization: deal with points outside of the viewable area
This implementation is a slightly modified version of the one found on http://graphics.lcs.mit.edu/~mcmillan/comp136/Lecture6/Lines.html
Windows has a fun little API function called LineDDA. This function has the following prototype: void LineDDA(int x1, int y1, int x2, int y2, callback, void* data);
(x1,y1) and (x2,y2) are the endpoints of a line segment. The function calculates every point which should be drawn if a straight line is drawn from one point to the other (excluding the exact point (x2,y2)). The callback function is called for each point which should be drawn. It is up to that function to do the actual drawing of the point.
This setup allows some nifty stuff to be done, such as the glyph lines we draw. Unfortunately, wxWidgets (as far as I can tell) does not offer a similar function. That is why this file exists. To provide us Linux people with a nifty feature.
LineDDA, if we can trust the name of the function, uses an algorithm known as Digital Differential Analyzer[1]. According to my research, this is one of the SLOWEST algorithms we could use[2]. Unfortunately, the fastest has a non-free license, so we can't use that. The second-fastest, however, has become a textbook case. It is called Wu's Symmetric Double-Step algorithm. I was unable to find anything that would imply we can't use it here. If anyone really objects to it, we can always step back to Bresenham's algoritm.
Parameters:
(x0,y0) - the first point on the line
(x1,y1) - the last point on the line. This point isn't actually drawn (to be consistent with the rest of the wx library).
setPixel - the function which draws the actual point
data - pointer to program-defined data object, passed to the callback function
LinePoints passes dc and data to the callback function. The callback function must have the following prototype. The name callback is a place holder.
void callback(int, int, void*);
If you want to draw something, make sure to send it in the void* structure.
Referenced by DrawLineContinue(), DrawLineTip(), GlyphLineDDAProc(), and LineTipDDAProc().