AutoREALM: Primitives.cpp File Reference
Primitives.cpp File Reference
#include <memory>
#include <wx/palette.h>
#include "Primitives.h"
#include "generic_library.h"
#include "maputils.h"
#include "types.h"
Functions
double GetAverageAngle (int i, int start, int last, int step, bool closed, VPoints points)
void Calc (int &i, int start, int last, int step, const VPoints &points, double &angle1, double &angle2, double &angle4, double &xofs1, double &xofs2, double &yofs1, double &yofs2, coord &x1, coord &y1, coord &x2, coord &y2, coord &x3, coord &y3, bool GetAverageSlope, bool ThickEnds, bool Closed, int &k, VPoints &ThickPoints, double &Thickness)
VPoints GetThickLines (const VPoints points, int &count, const StyleAttrib style, bool GetAverageSlope, bool ThickEnds, bool closed)
void DrawEnclosedFigure (wxDC *canvas, const VPoints &points, int count, bool closed, StyleAttrib &style, wxColour edgeColor, wxColour fillColor, ViewPoint view, bool GetAverageSlope)
wxString XMLIdFromCharId (wxChar c)
wxChar CharIdFromXMLId (wxString s, bool fractal)
void ReadOverlayColors (MainWin *win)
arRealRect AdjustToPrinterPage (arRealRect viewRect)
bool SetFractalState (bool current, FractalState state)
Variables
coord LastHandleX
coord LastHandleY
wxColour OverlayMainColor [maxOverlayColors]
wxColour OverlayFillColor [maxOverlayColors]
wxBitmap * HyperlinkBullet = NULL
Detailed Description
Function Documentation
arRealRect AdjustToPrinterPage (arRealRect viewRect)
Todo:
Code this
void Calc (int & i, int start, int last, int step, const VPoints & points, double & angle1, double & angle2, double & angle4, double & xofs1, double & xofs2, double & yofs1, double & yofs2, coord & x1, coord & y1, coord & x2, coord & y2, coord & x3, coord & y3, bool GetAverageSlope, bool ThickEnds, bool Closed, int & k, VPoints & ThickPoints, double & Thickness)
For a given point whose index is I, this routine calculates the next appropriate point in the object's "envelope" and adds it to the point list.
Parameters:
i The point index
start The index of the first point in the list. For thefirst side of the "envelope" this should be 0, and for the next side it should be count-1.
last The index of the last point in the list. For the first side of the "envelope" this should be count - 1, and for the next side it should be 0.
step This should be 1 for the first side of the "envelope" and -1 for the next side.
points The list of points which make up the line
References GetAverageAngle().
Referenced by GetThickLines().
void DrawEnclosedFigure (wxDC * canvas, const VPoints & points, int count, bool closed, StyleAttrib & style, wxColour edgeColor, wxColour fillColor, ViewPoint view, bool GetAverageSlope)
Todo:
The pascal sources for this included a routine named "CreatePaletteBrush" and "CreateHiresBrush". These functions look to create a simple brush of a given color for drawing, judging by the code. For now, that's what will be assumed, though it should be reviewed later to make sure this is what was intended.
Todo:
The following line of code does not compile, though docs say it should. This must be fixed.
Todo:
Original code: brushbitmap:=MainForm.FillPattern.GetMonochromeBitmap(Style.Fill);
Todo:
Here we run into some stickiness. We have a
Todo:
modify brush info here
References ViewPoint::DeltaCoordToScreen(), DrawLineContinue(), ViewPoint::FixStyle(), StyleAttrib::FullStyle, GetLineEnd(), GetLineStyleStart(), GetThickLines(), GridObject::GraphScale, GridObject::GraphUnitConvert, ViewPoint::grid, round(), TFullStyle::SThickness, TFullStyle::Thickness, and VSPointsToArray().
double GetAverageAngle (int i, int start, int last, int step, bool closed, VPoints points)
Todo:
Conflicts with definition in Primitives.h. Which is right? wxPalette FillPalette;
Starting at the line segment represented by points at I and I + Step, this routine tries to get the average angle by looking at the previous two and next two line segments if possible.
Parameters:
i The point index
start The index of the first point in the list. For the first side of the "envelope" this should be 0, and for the next side it should be count - 1.
last The index of the last point in the list. For the first side of the "envelope" this should be count - 1, and for the next side it should be 0.
step This should be 1 for the first side of the "envelope" and -1 for the next side.
closed This shows whether or not the figure is a close figure
points The list of points which make up the line
Returns:
Returns the average angle (which represents the average slope of the line segment) in radians.
References angle().
Referenced by Calc().
VPoints GetThickLines (const VPoints points, int & count, const StyleAttrib style, bool GetAverageSlope, bool ThickEnds, bool closed)
For an array of coordinates, this routine calculates a new set of coordinates that form an "envelope" around the original coordinates. The purpose of this routine is to allow rendering lines and curves where the width is a fixed amount (in map coordinates). Such objects always maintain a constant width relative to their size.
Parameters:
points The original point list
style The object's style (this now contains the optional numeric line width as well)
GetAverageSlope Used for curves and polycurves, this makes sure that the resulting "envelope" is smooth
ThickEnds Not used for now, this extends the endpoints by half the line width
closed If the polycurve is closed, this allows the original points to "wrap", and is necessary for GetAverageAngle to get the correct slope at the ends of the closed polycurve.
count (input) Contains the number of points in the original list (output) Returns the number of points in the new list
Returns:
Returns a list of points that form an "envelope" around the original object, with the specified numerical line width. This represents a single polygon to be filled.
References Calc(), StyleAttrib::FullStyle, and TFullStyle::SThickness.
Referenced by DrawEnclosedFigure().
void ReadOverlayColors (MainWin * win)
Todo:
Code this