AutoREALM: Primitives.h File Reference
Primitives.h File Reference
#include <set>
#include "globals.h"
#include "DrawLines.h"
#include "MainWin.h"
#include <wx/dcprint.h>
#include "ViewPoint.h"
Classes
struct TextAttrib
Typedefs
typedef std::set< bool > OverlaySet
typedef std::set
< HyperlinkFlagValues > HyperlinkFlags
typedef std::set< TextAttribType > TextAttribSet
Enumerations
enum HandleMode { hmAll = 0, hmOne, hmFoundFirst }
enum HyperlinkFlagValues { hyperExecute, hyperHidden }
enum TextAttribType {
tatText, tatFontName, tatFontSize, tatFontBold,
tatFontItalic, tatFontUnderline, tatAlignment, tatIconSize,
tatOutlineColor, tatHyperlinkText, tatHyperlinkFlags
}
enum FractalState { fsUnchanged, fsSetFractal, fsSetNormal, fsFlipFractal }
Functions
const wxString IconFontName (wxT("AutoREALMSymbols"))
void StartNewHandleDraw ()
void ReadOverlayColors ()
arRealRect AdjustToPrinterPage (arRealRect ViewRect)
VPoints GetThickLines (const VPoints points, int &count, const StyleAttrib style, bool GetAverageSlope, bool ThickEnds, bool closed)
void DrawEnclosedFigure (wxDC *canvas, const VPoints &points, int count, bool closed, StyleAttrib &style, wxColour edgeColor, wxColour fillColor, ViewPoint view, bool GetAverageSlope)
wxString XMLIdFromCharId (wxChar c)
wxChar CharIdFromXMLId (wxString s, bool fractal)
void ReadOverlayColors (MainWin *main)
bool SetFractalState (bool current, FractalState state)
Variables
const int QuickDraw_Fills = 0x00000001
const int QuickDraw_Lines = 0x00000002
const int QuickDraw_All = 0xFFFFFFFF
const int QuickDraw_None = 0x00000000
const int SelectDistance = 2
const double VeryClose = 1e-3
const wxColour FillPalette [12][10]
const int maxOverlayColors = 30
Detailed Description
Todo:
document all constants, typedefs, and other information in this file
Function Documentation
arRealRect AdjustToPrinterPage (arRealRect ViewRect)
Todo:
Code this
void DrawEnclosedFigure (wxDC * canvas, const VPoints & points, int count, bool closed, StyleAttrib & style, wxColour edgeColor, wxColour fillColor, ViewPoint view, bool GetAverageSlope)
Todo:
The pascal sources for this included a routine named "CreatePaletteBrush" and "CreateHiresBrush". These functions look to create a simple brush of a given color for drawing, judging by the code. For now, that's what will be assumed, though it should be reviewed later to make sure this is what was intended.
Todo:
The following line of code does not compile, though docs say it should. This must be fixed.
Todo:
Original code: brushbitmap:=MainForm.FillPattern.GetMonochromeBitmap(Style.Fill);
Todo:
Here we run into some stickiness. We have a
Todo:
modify brush info here
References ViewPoint::DeltaCoordToScreen(), DrawLineContinue(), ViewPoint::FixStyle(), StyleAttrib::FullStyle, GetLineEnd(), GetLineStyleStart(), GetThickLines(), GridObject::GraphScale, GridObject::GraphUnitConvert, ViewPoint::grid, round(), TFullStyle::SThickness, TFullStyle::Thickness, and VSPointsToArray().
VPoints GetThickLines (const VPoints points, int & count, const StyleAttrib style, bool GetAverageSlope, bool ThickEnds, bool closed)
For an array of coordinates, this routine calculates a new set of coordinates that form an "envelope" around the original coordinates. The purpose of this routine is to allow rendering lines and curves where the width is a fixed amount (in map coordinates). Such objects always maintain a constant width relative to their size.
Parameters:
points The original point list
style The object's style (this now contains the optional numeric line width as well)
GetAverageSlope Used for curves and polycurves, this makes sure that the resulting "envelope" is smooth
ThickEnds Not used for now, this extends the endpoints by half the line width
closed If the polycurve is closed, this allows the original points to "wrap", and is necessary for GetAverageAngle to get the correct slope at the ends of the closed polycurve.
count (input) Contains the number of points in the original list (output) Returns the number of points in the new list
Returns:
Returns a list of points that form an "envelope" around the original object, with the specified numerical line width. This represents a single polygon to be filled.
References Calc(), StyleAttrib::FullStyle, and TFullStyle::SThickness.
Referenced by DrawEnclosedFigure().
void ReadOverlayColors (MainWin * main)
Todo:
Code this
Variable Documentation
const wxColour FillPalette[12][10]
This is an array of colors which was defined by the ColorButton unit used in Delphi. It has been converted for use here, in case it is necessary for load/save of old maps.